//=====================================================================================================================================================================================================	
//	Global variables are defined here for use in other scripts.
//=====================================================================================================================================================================================================	


//=====================================================================================================================================================================================================	
//These imports must be included to cast the arrays
//=====================================================================================================================================================================================================	


#priority 9999

import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.oredict.IOreDict;
import crafttweaker.liquid.ILiquidStack;


//=====================================================================================================================================================================================================	
//	Creating Hashtables for all materials and their item forms.
//=====================================================================================================================================================================================================
/* - Notes on using these Glorious Global Goodies.

	These guys can be called like so:
		GlobalIngot["Iron"] = <ore:ingotIron>
		GlobalNugget["Copper"] = <ore:nuggetCopper>
	Returns an oredict bracket handler, so if you need an IItemStack, you can:
		GlobalNugget["Copper"].firstItem
	
	Can be used in loops to get just the string name as an "array":
	This will get you the nugget form of every material in the Ingot table.
		for item in GlobalIngot { GlobalNugget[item] }

	So, you just select the table that has the entries you want, 
	then call into other tables via the material name string
	This would be to add a tcon melting recipe for every molten fluid in the molten fluid table:
		for Liquid in GlobalMoltenMetal {
			mods.tconstruct.Melting.addRecipe( GlobalMoltenMetal[Liquid] * 144, GlobalIngot[Liquid], GlobalMeltingTemp[Liquid] );
		}

	Best to also include a null check in case an item is missing from a table
	otherwise the script will fail and error, which is not cash money.
	Ideally done for every table call which does look rediculous:
		for Liquid in GlobalMoltenMetal {
			if !( isNull(
				GlobalMoltenMetal[Liquid]
				&
				GlobalIngot[Liquid]  // Liquids cannot be null anyways, so this check is not necessary.
				&
				GlobalMeltingTemp[Liquid]
			) ) 
			{
				mods.tconstruct.Melting.addRecipe( GlobalMoltenMetal[Liquid] * 144, GlobalIngot[Liquid], GlobalMeltingTemp[Liquid] );
			}
		}

	I has a new thing to make these even better (Raw)

	The ability to combine a prefix and postfix for an oredictionary search so I can dynamically assemble all the oredictionary tables!
	This only works for oredictionries due to how they work.
	This will return <ore:ingotIron>:
		oreDict[ "ingot"~GlobalPostfixMetals["iron"] ]
	Now, the great thing about this is that it can be used in a loop.
	This loop will get you the oredictionaries for every ingot:
		for Metal in GlobalPostfixMetals {
			oreDict[ "ingot"~GlobalPostfixMetals["Metal"] ]
		}
	By their powers combined, you can get everything
	This retures ordictionaries for all the types and materials, 
	ingotIron, plateIron, ingotCopper, plateCopper and so on:
		for Metal in GlobalPostfixMetals {
			for Type in GlobalPrefixTypes {
				oreDict[ GlobalPrefixTypes[Type]~GlobalPostfixMetals["Metal"] ]

	getItem("minecraft:iron_ingot");  - I may be able to use this for dynamic variable combined itemstacks
		getItem( "minecraft:"~Metal~"_"~Type );
	Right now would only be useful on forging anvils as their item name is formatted as such.

*/


//=====================================================================================================================================================================================================	
//	Item Stack Tables
//=====================================================================================================================================================================================================


		//	Forging Anvils _______________________________________________________________________________________________________________________________________________________________________
	global GlobalAnvil as IItemStack[string] = {
		copper		:	<tinkersforging:tinkers_anvil/copper>,
		tin			:	<tinkersforging:tinkers_anvil/tin>,
		silver		:	<tinkersforging:tinkers_anvil/silver>,
		iron		:	<tinkersforging:tinkers_anvil/iron>,
		aluminum	:	<tinkersforging:tinkers_anvil/alumifun>,

		bronze		:	<tinkersforging:tinkers_anvil/bronze>,
		brass		:	<tinkersforging:tinkers_anvil/brass>,
		steel		:	<tinkersforging:tinkers_anvil/steel>,
	};

		//	Crossroads gears	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalCrossroadsGear as IItemStack[string] = {
		iron		:	<crossroads:gear_iron>,
		gold		:	<crossroads:gear_gold>,
		copper		:	<crossroads:gear_copper>,
		tin			:	<crossroads:gear_tin>,
		lead		:	<crossroads:gear_lead>,
		silver		:	<crossroads:gear_silver>,
		nickel		:	<crossroads:gear_nickel>,
	    bronze		:	<crossroads:gear_bronze>,
	    copshowium	:	<crossroads:gear_copshowium>,
		invar		:	<crossroads:gear_invar>,
		platinum	:	<crossroads:gear_platinum>,
		electrum	:	<crossroads:gear_electrum>,
	};

		//	Crossroads large Gears	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalCrossroadlargeGear as IItemStack[string] = {
		iron		:	<crossroads:large_gear_iron>,
		gold		:	<crossroads:large_gear_gold>,
		copper		:	<crossroads:large_gear_copper>,
		tin			:	<crossroads:large_gear_tin>,
		lead		:	<crossroads:large_gear_lead>,
		silver		:	<crossroads:large_gear_silver>,
		nickel		:	<crossroads:large_gear_nickel>,
		bronze		:	<crossroads:large_gear_bronze>,
	    copshowium	:	<crossroads:large_gear_copshowium>,
	    invar		:	<crossroads:large_gear_invar>,
		platinum	:	<crossroads:large_gear_platinum>,
		electrum	:	<crossroads:large_gear_electrum>,
	};

		//	Crossroads Toggle Gears	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalCrossroadToggleGear as IItemStack[string] = {
		iron		:	<crossroads:toggle_gear_iron>,
		gold		:	<crossroads:toggle_gear_gold>,
		copper		:	<crossroads:toggle_gear_copper>,
		tin			:	<crossroads:toggle_gear_tin>,
		lead		:	<crossroads:toggle_gear_lead>,
		silver		:	<crossroads:toggle_gear_silver>,
		nickel		:	<crossroads:toggle_gear_nickel>,
		bronze		:	<crossroads:toggle_gear_bronze>,
	    copshowium	:	<crossroads:toggle_gear_copshowium>,
	    invar		:	<crossroads:toggle_gear_invar>,
		platinum	:	<crossroads:toggle_gear_platinum>,
		electrum	:	<crossroads:toggle_gear_electrum>,
	};

		//	Tinker's Construct parts	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalTconParts as int[IItemStack] = {
		<tconstruct:sharpening_kit>		:	2,
		<tconstruct:pick_head>			:	2,
		<tconstruct:shovel_head>		:	2,
		<tconstruct:axe_head>			:	2,
		<tconstruct:broad_axe_head>		:	8,
		<tconstruct:sword_blade>		:	2,
		<tconstruct:large_sword_blade>	:	8,
		<tconstruct:hammer_head>		:	8,
		<tconstruct:excavator_head>		:	8,
		<tconstruct:scythe_head>		:	8,
		<tconstruct:large_plate>		:	8,
		<tconstruct:kama_head>			:	2,
		<tconstruct:arrow_head>			:	2,
		<tconstruct:pan_head>			:	3,
		<tconstruct:sign_head>			:	3,
		<tconstruct:tough_tool_rod>		:	3,
		<tconstruct:tough_binding>		:	3,
		<tconstruct:bow_limb>			:	3,
		<tconstruct:tool_rod>			:	1,
		<tconstruct:binding>			:	1,
		<tconstruct:wide_guard>			:	1,
		<tconstruct:hand_guard>			:	1,
		<tconstruct:cross_guard>		:	1,
		<tconstruct:knife_blade>		:	1,
		<conarm:polishing_kit>			:	3,
		<conarm:helmet_core>			:	4,
		<conarm:chest_core>				:	6,
		<conarm:leggings_core>			:	5,
		<conarm:boots_core>				:	4,
		<conarm:armor_plate>			:	3,
		<conarm:armor_trim>				:	1,
		<totaltinkers:greatbladecore>	:	12,
		<totaltinkers:fullguard>		:	3,
		<tcomplement:chisel_head>		:	1,
	};

		//	Wood Logs	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalWoodLogs as IItemStack[string] = {
		minecraft_oak				:	<minecraft:log:0>,
		minecraft_spruce			:	<minecraft:log:1>,
		minecraft_birch				:	<minecraft:log:2>,
		minecraft_jungle			:	<minecraft:log:3>,
		minecraft_acacia			:	<minecraft:log2:0>,
		minecraft_dark_oak			:	<minecraft:log2:1>,

		terraqueous_apple			:	<terraqueous:trunk1:0>,
		terraqueous_cherry			:	<terraqueous:trunk1:1>,
		terraqueous_orange			:	<terraqueous:trunk1:2>,
		terraqueous_pear			:	<terraqueous:trunk1:3>,
		terraqueous_peach			:	<terraqueous:trunk1:4>,
		terraqueous_mango			:	<terraqueous:trunk2:0>,
		terraqueous_lemon			:	<terraqueous:trunk2:1>,
		terraqueous_plum			:	<terraqueous:trunk2:2>,
		terraqueous_coconut			:	<terraqueous:trunk2:3>,
		terraqueous_banana			:	<terraqueous:trunk2:4>,

		biomesoplenty_sacred_oak	:	<biomesoplenty:log_0:4>,
		biomesoplenty_cherry		:	<biomesoplenty:log_0:5>,
		biomesoplenty_umbran		:	<biomesoplenty:log_0:6>,
		biomesoplenty_fir			:	<biomesoplenty:log_0:7>,
	};

		//	Wood Planks	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalWoodPlanks as IItemStack[string] = {
		minecraft_oak				:	<minecraft:planks:0>,
		minecraft_spruce			:	<minecraft:planks:1>,
		minecraft_birch				:	<minecraft:planks:2>,
		minecraft_jungle			:	<minecraft:planks:3>,
		minecraft_acacia			:	<minecraft:planks:4>,
		minecraft_dark_oak			:	<minecraft:planks:5>,

		terraqueous_apple 			:	<terraqueous:planks:0>,
		terraqueous_cherry 			:	<terraqueous:planks:1>,
		terraqueous_orange 			:	<terraqueous:planks:2>,
		terraqueous_pear 			:	<terraqueous:planks:3>,
		terraqueous_peach			:	<terraqueous:planks:4>,
		terraqueous_mango			:	<terraqueous:planks:5>,
		terraqueous_lemon			:	<terraqueous:planks:6>,
		terraqueous_plum			:	<terraqueous:planks:7>,
		terraqueous_coconut			:	<terraqueous:planks:8>,
		terraqueous_banana			:	<terraqueous:planks:9>,

		biomesoplenty_sacred_oak	:	<biomesoplenty:planks_0:0>,
		biomesoplenty_cherry		:	<biomesoplenty:planks_0:1>,
		biomesoplenty_umbran		:	<biomesoplenty:planks_0:2>,
		biomesoplenty_fir			:	<biomesoplenty:planks_0:3>,
	};

		//	Wood Slabs	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalWoodSlab as IItemStack[string] = {
		oak			:	<minecraft:wooden_slab:0>,
		spruce		:	<minecraft:wooden_slab:1>,
		birch		:	<minecraft:wooden_slab:2>,
		jungle		:	<minecraft:wooden_slab:3>,
		acacia		:	<minecraft:wooden_slab:4>,
		dark_oak	:	<minecraft:wooden_slab:5>,
	};

		//	Wood Stairs	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalWoodStair as IItemStack[string] = {
		oak			:	<minecraft:oak_stairs>,
		spruce		:	<minecraft:spruce_stairs>,
		birch		:	<minecraft:birch_stairs>,
		jungle		:	<minecraft:jungle_stairs>,
		acacia		:	<minecraft:acacia_stairs>,
		dark_oak	:	<minecraft:dark_oak_stairs>,
	};


//=====================================================================================================================================================================================================	
//	Ore Dictionary Tables
//=====================================================================================================================================================================================================


		//	Dynamic Oredictionary Assembly	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalPrefixTypes as string[string] = {
		ore			:	"ore",
    	oreChunk	:	"oreChunk",
		ingot       :   "ingot",
    	gem			:	"gem",
		block		:	"block",
		nugget		:	"nugget",
		chunk		:	"chunk",
		rockyChunk	:	"rockyChunk",
		crystal     :   "crystal",
    	shard       :   "shard",
    	clump       :   "clump",
    	dustDirty   :   "dustDirty",
    	dust        :   "dust",
    	plate       :   "plate",
    	stick       :   "stick",
		gear		:	"gear",
	};

		//	Dynamic Oredictionary Assembly	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalPostfixMetals as string[string] = {
		abyssum					:	"Abyssum",
		adamant					:	"Adamant",
		adamantine				:	"Adamantine",
		adamatine				:	"Adamatine",
		aeonsteel				:	"Aeonsteel",
		alduorite				:	"Alduorite",
		alnico					:	"Alnico",
		aluminum				:	"Aluminum",
		aluminumbrass			:	"Aluminumbrass",
		alumite					:	"Alumite",
		amber					:	"Amber",
		antimony				:	"Antimony",
		aquarium				:	"Aquarium",
		ardite					:	"Ardite",
		astralsilver			:	"Astralsilver",
		astrum					:	"Astrum",
		atlarus					:	"Atlarus",
		aurorum					:	"Aurorum",
		awakeddraconium			:	"Awakeddraconium",
		baseessence				:	"Baseessence",
		bassalt					:	"Bassalt",
		beryllium				:	"Beryllium",
		bismuth					:	"Bismuth",
		blackquartz				:	"Blackquartz",
		bloodbronze				:	"Bloodbronze",
		bloodinfusediron		:	"Bloodinfusediron",
		boron					:	"Boron",
		brass					:	"Brass",
		bronze					:	"Bronze",
		cadmium					:	"Cadmium",
		carmot					:	"Carmot",
		cerrosafe				:	"Cerrosafe",
		ceruclase				:	"Ceruclase",
		chromium				:	"Chromium",
		coal					:	"Coal",
		cobalt					:	"Cobalt",
		coldiron				:	"Coldiron",
		constantan				:	"Constantan",
		copper					:	"Copper",
		crystalized				:	"Crystalized",
		cupronickel				:	"Cupronickel",
		deepiron				:	"Deepiron",
		demonmetal				:	"Demonmetal",
		diamantine				:	"Diamantine",
		diamond					:	"Diamond",
		dilithium				:	"Dilithium",
		dogbearium				:	"Dogbearium",
		draconium				:	"Draconium",
		duranite				:	"Duranite",
		dyonite					:	"Dyonite",
		eezo					:	"Eezo",
		electrum				:	"Electrum",
		emeradic				:	"Emeradic",
		emerald					:	"Emerald",
		enchantedmetal			:	"Enchantedmetal",
		enderium				:	"Enderium",
		enderpearl				:	"Enderpearl",
		enoricrystal			:	"Enoricrystal",
		evilinfusedmetal		:	"Evilinfusedmetal",
		eximite					:	"Eximite",
		ferroboron				:	"Ferroboron",
		fiery					:	"Fiery",
		fractum					:	"Fractum",
		froststeel				:	"Froststeel",
		galvanizedsteel			:	"Galvanizedsteel",
		glowstone				:	"Glowstone",
		gold					:	"Gold",
		hardcarbon				:	"Hardcarbon",
		hardenedsteel			:	"Hardenedsteel",
		hslasteel				:	"Hslasteel",
		ignatius				:	"Ignatius",
		ignitz					:	"Ignitz",
		imperiomite				:	"Imperiomite",
		inertbloodiron			:	"Inertbloodiron",
		inferium				:	"Inferium",
		infuscolium				:	"Infuscolium",
		insanium				:	"Insanium",
		intermedium				:	"Intermedium",
		invar					:	"Invar",
		iox						:	"Iox",
		iridium					:	"Iridium",
		iron					:	"Iron",
		ironwood				:	"Ironwood",
		jade					:	"Jade",
		jaxum					:	"Jaxum",
		kalendrite				:	"Kalendrite",
		karmesine				:	"Karmesine",
		knightmetal				:	"Knightmetal",
		knightslime				:	"Knightslime",
		lapis					:	"Lapis",
		lead					:	"Lead",
		lemuurite				:	"Lemuurite",
		lithium					:	"Lithium",
		lockalloy				:	"Lockalloy",
		lumium					:	"Lumium",
		lumix					:	"Lumix",
		lutetium				:	"Lutetium",
		machalite				:	"Machalite",
		maganese				:	"Maganese",
		magmolybdochalkosmuth	:	"Magmolybdochalkosmuth",
		magnesium				:	"Magnesium",
		magnite					:	"Magnite",
		manganese				:	"Manganese",
		manylium				:	"Manylium",
		mercury					:	"Mercury",
		meteorite				:	"Meteorite",
		meutoite				:	"Meutoite",
		midasium				:	"Midasium",
		mithril					:	"Mithril",
		molybdochalkos			:	"Molybdochalkos",
		neptunium				:	"Neptunium",
		netherquartz			:	"Netherquartz",
		nichrome				:	"Nichrome",
		nickel					:	"Nickel",
		nihilite				:	"Nihilite",
		niob					:	"Niob",
		nucleum					:	"Nucleum",
		obsiderite				:	"Obsiderite",
		obsidian				:	"Obsidian",
		obsidiansteel			:	"Obsidiansteel",
		obsidiorite				:	"Obsidiorite",
		opal					:	"Opal",
		orichalcum				:	"Orichalcum",
		osglogloss				:	"Osglogloss",
		osmiridium				:	"Osmiridium",
		osmium					:	"Osmium",
		osram					:	"Osram",
		oureclasce				:	"Oureclasce",
		ovium					:	"Ovium",
		palis					:	"Palis",
		palladium				:	"Palladium",
		pandorium				:	"Pandorium",
		pewter					:	"Pewter",
		phosphorite				:	"Phosphorite",
		pigiron					:	"Pigiron",
		pinkslimeingot			:	"Pinkslimeingot",
		platinum				:	"Platinum",
		plutonium				:	"Plutonium",
		potash					:	"Potash",
		prometheum				:	"Prometheum",
		prometheum				:	"Prometheum",
		prometheum				:	"Prometheum",
		proxii					:	"Proxii",
		prudentium				:	"Prudentium",
		queensgold				:	"Queensgold",
		redstone				:	"Redstone",
		refinedglowstone		:	"Refinedglowstone",
		refinedobsidian			:	"Refinedobsidian",
		restonia				:	"Restonia",
		rosegold				:	"Rosegold",
		rubracium				:	"Rubracium",
		ruby					:	"Ruby",
		rutile					:	"Rutile",
		saguinite				:	"Saguinite",
		sapphire				:	"Sapphire",
		seismum					:	"Seismum",
		shadowiron				:	"Shadowiron",
		signalium				:	"Signalium",
		silicon					:	"Silicon",
		siliconcarbide			:	"Siliconcarbide",
		silver					:	"Silver",
		sinisterium				:	"Sinisterium",
		solarium				:	"Solarium",
		soulium					:	"Soulium",
		spectre					:	"Spectre",
		stainlesssteel			:	"Stainlesssteel",
		stalmetal				:	"Stalmetal",
		starsteel				:	"Starsteel",
		steel					:	"Steel",
		sulphur					:	"Sulphur",
		superium				:	"Superium",
		supremeum				:	"Supremeum",
		tantalum				:	"Tantalum",
		tanzanite				:	"Tanzanite",
		terrax					:	"Terrax",
		thorium					:	"Thorium",
		thortanium				:	"Thortanium",
		tiberium				:	"Tiberium",
		tin						:	"Tin",
		titanium				:	"Titanium",
		titaniumaluminum		:	"Titaniumaluminum",
		titaniumiridium			:	"Titaniumiridium",
		titiyum					:	"Titiyum",
		topaz					:	"Topaz",
		toughalloy				:	"Toughalloy",
		triberium				:	"Triberium",
		tritonite				:	"Tritonite",
		tungsten				:	"Tungsten",
		uranium					:	"Uranium",
		uru						:	"Uru",
		valyriuansteel			:	"Valyriuansteel",
		valyrium				:	"Valyrium",
		vibranium				:	"Vibranium",
		violium					:	"Violium",
		vulcanite				:	"Vulcanite",
		vyroxeres				:	"Vyroxeres",
		yrdeen					:	"Yrdeen",
		zinc					:	"Zinc",
		zirconium				:	"Zirconium",
	};

		//	Ore Blocks	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalOreBlock as IOreDictEntry[string] = {
		iron		:	<ore:oreIron>,
		gold		:	<ore:oreGold>,
		copper		:	<ore:oreCopper>,
		lead		:	<ore:oreLead>,
		cobalt		:	<ore:oreCobalt>,
		tungsten	:	<ore:oreTungsten>,
		aluminum	:	<ore:oreAluminum>,
		mithril		:	<ore:oreMithril>,
		nickel		:	<ore:oreNickel>,
		osmium		:	<ore:oreOsmium>,
		silver		:	<ore:oreSilver>,
		tin			:	<ore:oreTin>,
		zinc		:	<ore:oreZinc>,
		antimony	:	<ore:oreAntimony>,
		ardite		:	<ore:oreArdite>,
		beryllium	:	<ore:oreBeryllium>,
		bismuth		:	<ore:oreBismuth>,
		boron		:	<ore:oreBoron>,
		cadmium		:	<ore:oreCadmium>,
		chromium	:	<ore:oreChromium>,
		coldiron	:	<ore:oreColdiron>,
		dilithium	:	<ore:oreDilithium>,
		iridium		:	<ore:oreIridium>,
		lithium		:	<ore:oreLithium>,
		magnesium	:	<ore:oreMagnesium>,
		manganese	:	<ore:oreManganese>,
		mercury		:	<ore:oreMercury>,
		platinum	:	<ore:orePlatinum>,
		plutonium	:	<ore:orePlutonium>,
		rutile		:	<ore:oreRutile>,
		starsteel	:	<ore:oreStarsteel>,
		tantalum	:	<ore:oreTantalum>,
		thorium		:	<ore:oreThorium>,
		titanium	:	<ore:oreTitanium>,
		uranium		:	<ore:oreUranium>,
		zirconium	:	<ore:oreZirconium>,
	};

		//	Ore Chunks	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalOreChunk as IOreDictEntry[string] = {
		iron		:	<ore:oreChunkIron>,
		gold		:	<ore:oreChunkGold>,
		copper		:	<ore:oreChunkCopper>,
		lead		:	<ore:oreChunkLead>,
		cobalt		:	<ore:oreChunkCobalt>,
		tungsten	:	<ore:oreChunkTungsten>,
		aluminum	:	<ore:oreChunkAluminum>,
		mithril		:	<ore:oreChunkMithril>,
		nickel		:	<ore:oreChunkNickel>,
		osmium		:	<ore:oreChunkOsmium>,
		silver		:	<ore:oreChunkSilver>,
		tin			:	<ore:oreChunkTin>,
		zinc		:	<ore:oreChunkZinc>,
		antimony	:	<ore:oreChunkAntimony>,
		ardite		:	<ore:oreChunkArdite>,
		beryllium	:	<ore:oreChunkBeryllium>,
		bismuth		:	<ore:oreChunkBismuth>,
		boron		:	<ore:oreChunkBoron>,
		cadmium		:	<ore:oreChunkCadmium>,
		chromium	:	<ore:oreChunkChromium>,
		coldiron	:	<ore:oreChunkColdiron>,
		dilithium	:	<ore:oreChunkDilithium>,
		iridium		:	<ore:oreChunkIridium>,
		lithium		:	<ore:oreChunkLithium>,
		magnesium	:	<ore:oreChunkMagnesium>,
		manganese	:	<ore:oreChunkManganese>,
		mercury		:	<ore:oreChunkMercury>,
		platinum	:	<ore:oreChunkPlatinum>,
		plutonium	:	<ore:oreChunkPlutonium>,
		rutile		:	<ore:oreChunkRutile>,
		starsteel	:	<ore:oreChunkStarsteel>,
		tantalum	:	<ore:oreChunkTantalum>,
		thorium		:	<ore:oreChunkThorium>,
		titanium	:	<ore:oreChunkTitanium>,
		uranium		:	<ore:oreChunkUranium>,
		zirconium	:	<ore:oreChunkZirconium>,
	};

		//	Ingots	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalIngot as IOreDictEntry[string] = {
		iron					:	<ore:ingotIron>,
		gold					:	<ore:ingotGold>,
		copper					:	<ore:ingotCopper>,
		lead					:	<ore:ingotLead>,
		cobalt					:	<ore:ingotCobalt>,
		tungsten				:	<ore:ingotTungsten>,
		aluminum				:	<ore:ingotAluminum>,
		mithril					:	<ore:ingotMithril>,
		nickel					:	<ore:ingotNickel>,
		osmium					:	<ore:ingotOsmium>,
		silver					:	<ore:ingotSilver>,
		tin						:	<ore:ingotTin>,
		zinc					:	<ore:ingotZinc>,
		antimony				:	<ore:ingotAntimony>,
		ardite					:	<ore:ingotArdite>,
		beryllium				:	<ore:ingotBeryllium>,
		bismuth					:	<ore:ingotBismuth>,
		boron					:	<ore:ingotBoron>,
		cadmium					:	<ore:ingotCadmium>,
		chromium				:	<ore:ingotChromium>,
		coldiron				:	<ore:ingotColdiron>,
		dilithium				:	<ore:ingotDilithium>,
		iridium					:	<ore:ingotIridium>,
		lithium					:	<ore:ingotLithium>,
		magnesium				:	<ore:ingotMagnesium>,
		manganese				:	<ore:ingotManganese>,
		mercury					:	<ore:ingotMercury>,
		platinum				:	<ore:ingotPlatinum>,
		plutonium				:	<ore:ingotPlutonium>,
		rutile					:	<ore:ingotRutile>,
		starsteel				:	<ore:ingotStarsteel>,
		tantalum				:	<ore:ingotTantalum>,
		thorium					:	<ore:ingotThorium>,
		titanium				:	<ore:ingotTitanium>,
		uranium					:	<ore:ingotUranium>,
		zirconium				:	<ore:ingotZirconium>,

		bronze					:	<ore:ingotBronze>,
	    copshowium				:	<ore:ingotCopshowium>,
	    invar					:	<ore:ingotInvar>,
		electrum				:	<ore:ingotElectrum>,

		xu_enchanted_metal		:	<ore:ingotEnchantedMetal>,
		uranium					:	<ore:ingotUranium>,
		ferroboron				:	<ore:ingotFerroboron>,
		knightslime				:	<ore:ingotKnightslime>,
		insanium				:	<ore:ingotInsanium>,
		baseEssence				:	<ore:ingotBaseEssence>,
		inferium				:	<ore:ingotInferium>,
		prudentium				:	<ore:ingotPrudentium>,
		intermedium				:	<ore:ingotIntermedium>,
		superium				:	<ore:ingotSuperium>,
		supremium				:	<ore:ingotSupremium>,
		soulium					:	<ore:ingotSoulium>,
		manganese				:	<ore:ingotManganese>,
		lithiumManganeseDioxide	:	<ore:ingotLithiumManganeseDioxide>,
		hSLASteel				:	<ore:ingotHSLASteel>,
		siliconCarbide			:	<ore:ingotSiliconCarbide>,
		copshowium				:	<ore:ingotCopshowium>,
		osmiridium				:	<ore:ingotOsmiridium>,
		tough					:	<ore:ingotTough>,
		siCSiCCMC				:	<ore:ingotSiCSiCCMC>,
		pigiron					:	<ore:ingotPigiron>,
		elementium				:	<ore:ingotElementium>,
		electrotineAlloy		:	<ore:ingotElectrotineAlloy>,
		redAlloy				:	<ore:ingotRedAlloy>,
		carbon					:	<ore:ingotCarbon>,
		alubrass				:	<ore:ingotAlubrass>,
		fireDragonsteel			:	<ore:ingotFireDragonsteel>,
		manasteel				:	<ore:ingotManasteel>,
		mirion					:	<ore:ingotMirion>,
		extreme					:	<ore:ingotExtreme>,
		xu_evil_metal			:	<ore:ingotEvilMetal>,
		osgloglas				:	<ore:ingotOsgloglas>,
		obsidianSteel			:	<ore:ingotObsidianSteel>,
		unstable				:	<ore:ingotUnstable>,
		redstone				:	<ore:ingotRedstone>,
		thermoconducting		:	<ore:ingotThermoconducting>,
		terrasteel				:	<ore:ingotTerrasteel>,
		alumite					:	<ore:ingotAlumite>,
		iceDragonsteel			:	<ore:ingotIceDragonsteel>,
		magnesiumDiboride		:	<ore:ingotMagnesiumDiboride>,
		shibuichi				:	<ore:ingotShibuichi>,
		tinSilver				:	<ore:ingotTinSilver>,
		leadPlatinum			:	<ore:ingotLeadPlatinum>,
		zircaloy				:	<ore:ingotZircaloy>,
		manyullyn				:	<ore:ingotManyullyn>,
		xu_demonic_metal		:	<ore:ingotDemonicMetal>,
		refinedGlowstone		:	<ore:ingotRefinedGlowstone>,
	};

		//	Gems	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalGem as IOreDictEntry[string] = {
		amber		:	<ore:gemEnderBiotite>,
		amethyst	:	<ore:gemAmethyst>,
		ruby		:	<ore:gemRuby>,
		peridot		:	<ore:gemPeridot>,
		topaz		:	<ore:gemTopaz>,
		tanzanite	:	<ore:gemTanzanite>,
		malachite	:	<ore:gemMalachite>,
		sapphire	:	<ore:gemSapphire>,
		amber		:	<ore:gemAmber>,
		lapis		:	<ore:gemLapis>,
		blackQuartz	:	<ore:gemQuartzBlack>,
		redstone	:	<ore:dustRedstone>,
		aquamarine	:	<ore:gemAquamarine>,
		emerald		:	<ore:gemEmerald>,
		diamond		:	<ore:gemDiamond>,
	};

		//	Blocks	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalBlock as IOreDictEntry[string] = {
		iron		:	<ore:blockIron>,
		gold		:	<ore:blockGold>,
		copper		:	<ore:blockCopper>,
		lead		:	<ore:blockLead>,
		cobalt		:	<ore:blockCobalt>,
		tungsten	:	<ore:blockTungsten>,
		aluminum	:	<ore:blockAluminum>,
		mithril		:	<ore:blockMithril>,
		nickel		:	<ore:blockNickel>,
		osmium		:	<ore:blockOsmium>,
		silver		:	<ore:blockSilver>,
		tin			:	<ore:blockTin>,
		zinc		:	<ore:blockZinc>,
		antimony	:	<ore:blockAntimony>,
		ardite		:	<ore:blockArdite>,
		beryllium	:	<ore:blockBeryllium>,
		bismuth		:	<ore:blockBismuth>,
		boron		:	<ore:blockBoron>,
		cadmium		:	<ore:blockCadmium>,
		chromium	:	<ore:blockChromium>,
		coldiron	:	<ore:blockColdiron>,
		dilithium	:	<ore:blockDilithium>,
		iridium		:	<ore:blockIridium>,
		lithium		:	<ore:blockLithium>,
		magnesium	:	<ore:blockMagnesium>,
		manganese	:	<ore:blockManganese>,
		mercury		:	<ore:blockMercury>,
		platinum	:	<ore:blockPlatinum>,
		plutonium	:	<ore:blockPlutonium>,
		rutile		:	<ore:blockRutile>,
		starsteel	:	<ore:blockStarsteel>,
		tantalum	:	<ore:blockTantalum>,
		thorium		:	<ore:blockThorium>,
		titanium	:	<ore:blockTitanium>,
		uranium		:	<ore:blockUranium>,
		zirconium	:	<ore:blockZirconium>,
	};

		//	Nuggets	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalNugget as IOreDictEntry[string] = {
		iron		:	<ore:nuggetIron>,
		gold		:	<ore:nuggetGold>,
		copper		:	<ore:nuggetCopper>,
		lead		:	<ore:nuggetLead>,
		cobalt		:	<ore:nuggetCobalt>,
		tungsten	:	<ore:nuggetTungsten>,
		aluminum	:	<ore:nuggetAluminum>,
		mithril		:	<ore:nuggetMithril>,
		nickel		:	<ore:nuggetNickel>,
		osmium		:	<ore:nuggetOsmium>,
		silver		:	<ore:nuggetSilver>,
		tin			:	<ore:nuggetTin>,
		zinc		:	<ore:nuggetZinc>,
		antimony	:	<ore:nuggetAntimony>,
		ardite		:	<ore:nuggetArdite>,
		beryllium	:	<ore:nuggetBeryllium>,
		bismuth		:	<ore:nuggetBismuth>,
		boron		:	<ore:nuggetBoron>,
		cadmium		:	<ore:nuggetCadmium>,
		chromium	:	<ore:nuggetChromium>,
		coldiron	:	<ore:nuggetColdiron>,
		dilithium	:	<ore:nuggetDilithium>,
		iridium		:	<ore:nuggetIridium>,
		lithium		:	<ore:nuggetLithium>,
		magnesium	:	<ore:nuggetMagnesium>,
		manganese	:	<ore:nuggetManganese>,
		mercury		:	<ore:nuggetMercury>,
		platinum	:	<ore:nuggetPlatinum>,
		plutonium	:	<ore:nuggetPlutonium>,
		rutile		:	<ore:nuggetRutile>,
		starsteel	:	<ore:nuggetStarsteel>,
		tantalum	:	<ore:nuggetTantalum>,
		thorium		:	<ore:nuggetThorium>,
		titanium	:	<ore:nuggetTitanium>,
		uranium		:	<ore:nuggetUranium>,
		zirconium	:	<ore:nuggetZirconium>,

		bronze		:	<ore:nuggetBronze>,
	    copshowium	:	<ore:nuggetCopshowium>,
	    invar		:	<ore:nuggetInvar>,
		platinum	:	<ore:nuggetPlatinum>,
		electrum	:	<ore:nuggetElectrum>,

		thorium		:	<ore:dustTinyDust>,
		lithium		:	<ore:dustTinyDust>,
	};

		//	Magneticraft Chunks	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalChunk as IOreDictEntry[string] = {
		iron		:	<ore:chunkIron>,
		gold		:	<ore:chunkGold>,
		copper		:	<ore:chunkCopper>,
		lead		:	<ore:chunkLead>,
		cobalt		:	<ore:chunkCobalt>,
		tungsten	:	<ore:chunkTungsten>,
		aluminum	:	<ore:chunkAluminum>,
		mithril		:	<ore:chunkMithril>,
		nickel		:	<ore:chunkNickel>,
		osmium		:	<ore:chunkOsmium>,
		silver		:	<ore:chunkSilver>,
		tin			:	<ore:chunkTin>,
		zinc		:	<ore:chunkZinc>,
		antimony	:	<ore:chunkAntimony>,
		ardite		:	<ore:chunkArdite>,
		beryllium	:	<ore:chunkBeryllium>,
		bismuth		:	<ore:chunkBismuth>,
		boron		:	<ore:chunkBoron>,
		cadmium		:	<ore:chunkCadmium>,
		chromium	:	<ore:chunkChromium>,
		coldiron	:	<ore:chunkColdiron>,
		dilithium	:	<ore:chunkDilithium>,
		iridium	:	<ore:chunkIridium>,
		lithium	:	<ore:chunkLithium>,
		magnesium	:	<ore:chunkMagnesium>,
		manganese	:	<ore:chunkManganese>,
		mercury	:	<ore:chunkMercury>,
		platinum	:	<ore:chunkPlatinum>,
		plutonium	:	<ore:chunkPlutonium>,
		rutile	:	<ore:chunkRutile>,
		starsteel	:	<ore:chunkStarsteel>,
		tantalum	:	<ore:chunkTantalum>,
		thorium	:	<ore:chunkThorium>,
		titanium	:	<ore:chunkTitanium>,
		uranium	:	<ore:chunkUranium>,
		zirconium	:	<ore:chunkZirconium>,
	};

		//	Magneticraft Rocky Chunks	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalRockyChunk as IOreDictEntry[string] = {
		iron	:	<ore:rockyChunkIron>,
		gold	:	<ore:rockyChunkGold>,
		copper	:	<ore:rockyChunkCopper>,
		lead	:	<ore:rockyChunkLead>,
		cobalt	:	<ore:rockyChunkCobalt>,
		tungsten	:	<ore:rockyChunkTungsten>,
		aluminum	:	<ore:rockyChunkAluminum>,
		mithril	:	<ore:rockyChunkMithril>,
		nickel	:	<ore:rockyChunkNickel>,
		osmium	:	<ore:rockyChunkOsmium>,
		silver	:	<ore:rockyChunkSilver>,
		tin	:	<ore:rockyChunkTin>,
		zinc	:	<ore:rockyChunkZinc>,
		antimony	:	<ore:rockyChunkAntimony>,
		ardite	:	<ore:rockyChunkArdite>,
		beryllium	:	<ore:rockyChunkBeryllium>,
		bismuth	:	<ore:rockyChunkBismuth>,
		boron	:	<ore:rockyChunkBoron>,
		cadmium	:	<ore:rockyChunkCadmium>,
		chromium	:	<ore:rockyChunkChromium>,
		coldiron	:	<ore:rockyChunkColdiron>,
		dilithium	:	<ore:rockyChunkDilithium>,
		iridium	:	<ore:rockyChunkIridium>,
		lithium	:	<ore:rockyChunkLithium>,
		magnesium	:	<ore:rockyChunkMagnesium>,
		manganese	:	<ore:rockyChunkManganese>,
		mercury	:	<ore:rockyChunkMercury>,
		platinum	:	<ore:rockyChunkPlatinum>,
		plutonium	:	<ore:rockyChunkPlutonium>,
		rutile	:	<ore:rockyChunkRutile>,
		starsteel	:	<ore:rockyChunkStarsteel>,
		tantalum	:	<ore:rockyChunkTantalum>,
		thorium	:	<ore:rockyChunkThorium>,
		titanium	:	<ore:rockyChunkTitanium>,
		uranium	:	<ore:rockyChunkUranium>,
		zirconium	:	<ore:rockyChunkZirconium>,
	};

		//	Dusts	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalDust as IOreDictEntry[string] = {
		iron	:	<ore:dustIron>,
		gold	:	<ore:dustGold>,
		copper	:	<ore:dustCopper>,
		lead	:	<ore:dustLead>,
		cobalt	:	<ore:dustCobalt>,
		tungsten	:	<ore:dustTungsten>,
		aluminum	:	<ore:dustAluminum>,
		mithril	:	<ore:dustMithril>,
		nickel	:	<ore:dustNickel>,
		osmium	:	<ore:dustOsmium>,
		silver	:	<ore:dustSilver>,
		tin	:	<ore:dustTin>,
		zinc	:	<ore:dustZinc>,
		antimony	:	<ore:dustAntimony>,
		ardite	:	<ore:dustArdite>,
		beryllium	:	<ore:dustBeryllium>,
		bismuth	:	<ore:dustBismuth>,
		boron	:	<ore:dustBoron>,
		cadmium	:	<ore:dustCadmium>,
		chromium	:	<ore:dustChromium>,
		coldiron	:	<ore:dustColdiron>,
		dilithium	:	<ore:dustDilithium>,
		iridium	:	<ore:dustIridium>,
		lithium	:	<ore:dustLithium>,
		magnesium	:	<ore:dustMagnesium>,
		manganese	:	<ore:dustManganese>,
		mercury	:	<ore:dustMercury>,
		platinum	:	<ore:dustPlatinum>,
		plutonium	:	<ore:dustPlutonium>,
		rutile	:	<ore:dustRutile>,
		starsteel	:	<ore:dustStarsteel>,
		tantalum	:	<ore:dustTantalum>,
		thorium	:	<ore:dustThorium>,
		titanium	:	<ore:dustTitanium>,
		uranium	:	<ore:dustUranium>,
		zirconium	:	<ore:dustZirconium>,
	};

		//	Mekanism DirtyDusts	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalDustDirty as IOreDictEntry[string] = {
		iron	:	<ore:dustDirtyIron>,
		gold	:	<ore:dustDirtyGold>,
		copper	:	<ore:dustDirtyCopper>,
		lead	:	<ore:dustDirtyLead>,
		cobalt	:	<ore:dustDirtyCobalt>,
		tungsten	:	<ore:dustDirtyTungsten>,
		aluminum	:	<ore:dustDirtyAluminum>,
		mithril	:	<ore:dustDirtyMithril>,
		nickel	:	<ore:dustDirtyNickel>,
		osmium	:	<ore:dustDirtyOsmium>,
		silver	:	<ore:dustDirtySilver>,
		tin	:	<ore:dustDirtyTin>,
		zinc	:	<ore:dustDirtyZinc>,
		antimony	:	<ore:dustDirtyAntimony>,
		ardite	:	<ore:dustDirtyArdite>,
		beryllium	:	<ore:dustDirtyBeryllium>,
		bismuth	:	<ore:dustDirtyBismuth>,
		boron	:	<ore:dustDirtyBoron>,
		cadmium	:	<ore:dustDirtyCadmium>,
		chromium	:	<ore:dustDirtyChromium>,
		coldiron	:	<ore:dustDirtyColdiron>,
		dilithium	:	<ore:dustDirtyDilithium>,
		iridium	:	<ore:dustDirtyIridium>,
		lithium	:	<ore:dustDirtyLithium>,
		magnesium	:	<ore:dustDirtyMagnesium>,
		manganese	:	<ore:dustDirtyManganese>,
		mercury	:	<ore:dustDirtyMercury>,
		platinum	:	<ore:dustDirtyPlatinum>,
		plutonium	:	<ore:dustDirtyPlutonium>,
		rutile	:	<ore:dustDirtyRutile>,
		starsteel	:	<ore:dustDirtyStarsteel>,
		tantalum	:	<ore:dustDirtyTantalum>,
		thorium	:	<ore:dustDirtyThorium>,
		titanium	:	<ore:dustDirtyTitanium>,
		uranium	:	<ore:dustDirtyUranium>,
		zirconium	:	<ore:dustDirtyZirconium>,
	};

		//	Mekanism Clumps	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalClump as IOreDictEntry[string] = {
		iron	:	<ore:clumpIron>,
		gold	:	<ore:clumpGold>,
		copper	:	<ore:clumpCopper>,
		lead	:	<ore:clumpLead>,
		cobalt	:	<ore:clumpCobalt>,
		tungsten	:	<ore:clumpTungsten>,
		aluminum	:	<ore:clumpAluminum>,
		mithril	:	<ore:clumpMithril>,
		nickel	:	<ore:clumpNickel>,
		osmium	:	<ore:clumpOsmium>,
		silver	:	<ore:clumpSilver>,
		tin	:	<ore:clumpTin>,
		zinc	:	<ore:clumpZinc>,
		antimony	:	<ore:clumpAntimony>,
		ardite	:	<ore:clumpArdite>,
		beryllium	:	<ore:clumpBeryllium>,
		bismuth	:	<ore:clumpBismuth>,
		boron	:	<ore:clumpBoron>,
		cadmium	:	<ore:clumpCadmium>,
		chromium	:	<ore:clumpChromium>,
		coldiron	:	<ore:clumpColdiron>,
		dilithium	:	<ore:clumpDilithium>,
		iridium	:	<ore:clumpIridium>,
		lithium	:	<ore:clumpLithium>,
		magnesium	:	<ore:clumpMagnesium>,
		manganese	:	<ore:clumpManganese>,
		mercury	:	<ore:clumpMercury>,
		platinum	:	<ore:clumpPlatinum>,
		plutonium	:	<ore:clumpPlutonium>,
		rutile	:	<ore:clumpRutile>,
		starsteel	:	<ore:clumpStarsteel>,
		tantalum	:	<ore:clumpTantalum>,
		thorium	:	<ore:clumpThorium>,
		titanium	:	<ore:clumpTitanium>,
		uranium	:	<ore:clumpUranium>,
		zirconium	:	<ore:clumpZirconium>,
	};

		//	Plates	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalPlate as IOreDictEntry[string] = {
		iron	:	<ore:plateIron>,
		gold	:	<ore:plateGold>,
		copper	:	<ore:plateCopper>,
		lead	:	<ore:plateLead>,
		cobalt	:	<ore:plateCobalt>,
		tungsten	:	<ore:plateTungsten>,
		aluminum	:	<ore:plateAluminum>,
		mithril	:	<ore:plateMithril>,
		nickel	:	<ore:plateNickel>,
		osmium	:	<ore:plateOsmium>,
		silver	:	<ore:plateSilver>,
		tin	:	<ore:plateTin>,
		zinc	:	<ore:plateZinc>,
		antimony	:	<ore:plateAntimony>,
		ardite	:	<ore:plateArdite>,
		beryllium	:	<ore:plateBeryllium>,
		bismuth	:	<ore:plateBismuth>,
		boron	:	<ore:plateBoron>,
		cadmium	:	<ore:plateCadmium>,
		chromium	:	<ore:plateChromium>,
		coldiron	:	<ore:plateColdiron>,
		dilithium	:	<ore:plateDilithium>,
		iridium	:	<ore:plateIridium>,
		lithium	:	<ore:plateLithium>,
		magnesium	:	<ore:plateMagnesium>,
		manganese	:	<ore:plateManganese>,
		mercury	:	<ore:plateMercury>,
		platinum	:	<ore:platePlatinum>,
		plutonium	:	<ore:platePlutonium>,
		rutile	:	<ore:plateRutile>,
		starsteel	:	<ore:plateStarsteel>,
		tantalum	:	<ore:plateTantalum>,
		thorium	:	<ore:plateThorium>,
		titanium	:	<ore:plateTitanium>,
		uranium	:	<ore:plateUranium>,
		zirconium	:	<ore:plateZirconium>,

		bronze	:	<ore:plateBronze>,
		brass	:	<ore:plateBrass>,
		steel	:	<ore:plateSteel>,

		copshowium	:	<ore:plateCopshowium>,
	    invar	:	<ore:plateInvar>,
		platinum	:	<ore:platePlatinum>,
		electrum	:	<ore:plateElectrum>,
	};

		//	Sticks	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalStick as IOreDictEntry[string] = {
		iron	:	<ore:stickIron>,
		gold	:	<ore:stickGold>,
		copper	:	<ore:stickCopper>,
		lead	:	<ore:stickLead>,
		cobalt	:	<ore:stickCobalt>,
		tungsten	:	<ore:stickTungsten>,
		aluminum	:	<ore:stickAluminum>,
		mithril	:	<ore:stickMithril>,
		nickel	:	<ore:stickNickel>,
		osmium	:	<ore:stickOsmium>,
		silver	:	<ore:stickSilver>,
		tin	:	<ore:stickTin>,
		zinc	:	<ore:stickZinc>,
		antimony	:	<ore:stickAntimony>,
		ardite	:	<ore:stickArdite>,
		beryllium	:	<ore:stickBeryllium>,
		bismuth	:	<ore:stickBismuth>,
		boron	:	<ore:stickBoron>,
		cadmium	:	<ore:stickCadmium>,
		chromium	:	<ore:stickChromium>,
		coldiron	:	<ore:stickColdiron>,
		dilithium	:	<ore:stickDilithium>,
		iridium	:	<ore:stickIridium>,
		lithium	:	<ore:stickLithium>,
		magnesium	:	<ore:stickMagnesium>,
		manganese	:	<ore:stickManganese>,
		mercury	:	<ore:stickMercury>,
		platinum	:	<ore:stickPlatinum>,
		plutonium	:	<ore:stickPlutonium>,
		rutile	:	<ore:stickRutile>,
		starsteel	:	<ore:stickStarsteel>,
		tantalum	:	<ore:stickTantalum>,
		thorium	:	<ore:stickThorium>,
		titanium	:	<ore:stickTitanium>,
		uranium	:	<ore:stickUranium>,
		zirconium	:	<ore:stickZirconium>,

		bronze	:	<ore:stickBronze>,
		brass	:	<ore:stickBrass>,
		steel	:	<ore:stickSteel>,
	};

		//	Gears	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalGear as IOreDictEntry[string] = {
		iron	:	<ore:gearIron>,
		gold	:	<ore:gearGold>,
		copper	:	<ore:gearCopper>,
		lead	:	<ore:gearLead>,
		cobalt	:	<ore:gearCobalt>,
		tungsten	:	<ore:gearTungsten>,
		aluminum	:	<ore:gearAluminum>,
		mithril	:	<ore:gearMithril>,
		nickel	:	<ore:gearNickel>,
		osmium	:	<ore:gearOsmium>,
		silver	:	<ore:gearSilver>,
		tin	:	<ore:gearTin>,
		zinc	:	<ore:gearZinc>,
		antimony	:	<ore:gearAntimony>,
		ardite	:	<ore:gearArdite>,
		beryllium	:	<ore:gearBeryllium>,
		bismuth	:	<ore:gearBismuth>,
		boron	:	<ore:gearBoron>,
		cadmium	:	<ore:gearCadmium>,
		chromium	:	<ore:gearChromium>,
		coldiron	:	<ore:gearColdiron>,
		dilithium	:	<ore:gearDilithium>,
		iridium	:	<ore:gearIridium>,
		lithium	:	<ore:gearLithium>,
		magnesium	:	<ore:gearMagnesium>,
		manganese	:	<ore:gearManganese>,
		mercury	:	<ore:gearMercury>,
		platinum	:	<ore:gearPlatinum>,
		plutonium	:	<ore:gearPlutonium>,
		rutile	:	<ore:gearRutile>,
		starsteel	:	<ore:gearStarsteel>,
		tantalum	:	<ore:gearTantalum>,
		thorium	:	<ore:gearThorium>,
		titanium	:	<ore:gearTitanium>,
		uranium	:	<ore:gearUranium>,
		zirconium	:	<ore:gearZirconium>,

		bronze	:	<ore:gearBronze>,
		brass	:	<ore:gearBrass>,
		steel	:	<ore:gearSteel>,
	};


//=====================================================================================================================================================================================================	
//	Fluid Tables Liquids must actually be loaded in the game, otherwise script will error
//=====================================================================================================================================================================================================


	//	Molten Metals _______________________________________________________________________________________________________________________________________________________________________
	global GlobalMoltenMetal as ILiquidStack[string] = {
		iron	:	<liquid:iron>,
		gold	:	<liquid:gold>,
		copper	:	<liquid:copper>,
		lead	:	<liquid:lead>,
		cobalt	:	<liquid:cobalt>,
		tungsten	:	<liquid:tungsten>,
		aluminum	:	<liquid:aluminum>,
		mithril	:	<liquid:mithril>,
		nickel	:	<liquid:nickel>,
		osmium	:	<liquid:osmium>,
		silver	:	<liquid:silver>,
		tin	:	<liquid:tin>,
		zinc	:	<liquid:zinc>,
		antimony	:	<liquid:antimony>,
		ardite	:	<liquid:ardite>,
		beryllium	:	<liquid:beryllium>,
		bismuth	:	<liquid:bismuth>,
		boron	:	<liquid:boron>,
		cadmium	:	<liquid:cadmium>,
		chromium	:	<liquid:chromium>,
		coldiron	:	<liquid:coldiron>,
		dilithium	:	<liquid:dilithium_fluid>,
		iridium	:	<liquid:iridium>,
		lithium	:	<liquid:lithium>,
		magnesium	:	<liquid:magnesium>,
		manganese	:	<liquid:manganese>,
		mercury	:	<liquid:mercury>,
		platinum	:	<liquid:platinum>,
		plutonium	:	<liquid:plutonium>,
		rutile	:	<liquid:rutile>,
		starsteel	:	<liquid:starsteel>,
		tantalum	:	<liquid:tantalum>,
		thorium	:	<liquid:thorium>,
		titanium	:	<liquid:titanium>,
		uranium	:	<liquid:uranium>,
		zirconium	:	<liquid:zirconium>,

		bronze	:	<liquid:bronze>,
		brass	:	<liquid:brass>,
		steel	:	<liquid:steel>,	

	    copshowium	:	<liquid:copshowium>,
	    invar	:	<liquid:invar>,
		electrum	:	<liquid:electrum>,
	};


//=====================================================================================================================================================================================================	
//	Technical Tables
//=====================================================================================================================================================================================================


		//	Melting Temperatures _______________________________________________________________________________________________________________________________________________________________________
	global GlobalMeltingTemp as int[string] = {
		iron		:	1855,
		gold		:	1300,
		copper		:	1300,
		lead		:	627,
		cobalt		:	1795,
		tungsten	:	3722,
		aluminum	:	960,
		mithril		:	2600,
		nickel		:	1755,
		osmium		:	3350,
		silver		:	1261,
		tin			:	532,
		zinc		:	719,
		antimony	:	930,
		ardite		:	2100,
		beryllium	:	1587,
		bismuth		:	571,
		boron		:	2300,
		cadmium		:	621,
		chromium	:	2207,
		coldiron	:	2400,
		dilithium	:	650,
		iridium		:	2754,
		lithium		:	480,
		magnesium	:	950,
		manganese	:	1546,
		mercury		:	262,
		platinum	:	2068,
		plutonium	:	939,
		rutile		:	1968,
		starsteel	:	2700,
		tantalum	:	3266,
		thorium		:	2055,
		titanium	:	1968,
		uranium		:	1432,
		zirconium	:	2155,

		bronze		:	1250,
		brass		:	1200,
		steel		:	1670,
	};

		//	Harvest Levels (Needs refinement) _______________________________________________________________________________________________________________________________________________________________________
	global GlobalHarvestLevel as int[string] = {
		copper	:	1,
		lead	:	1,
		lithium	:	1,
		tin		:	1,
		bismuth	:	2,
		bronze	:	2,
		cadmium	:	2,
		gold	:	2,
		magnesium	:	2,
		molybdochalkos	:	2,
		cerrosafe	:	3,
		magmolybdochalkosmuth	:	3,
		rosegold	:	3,
		silver	:	3,
		zinc	:	3,
		aluminum	:	4,
		brass	:	4,
		electrum	:	4,
		iron	:	4,
		beryllium	:	5,
		galvanizedsteel	:	5,
		nickel	:	5,
		palladium	:	5,
		steel	:	5,
		alumite	:	6,
		cobalt	:	6,
		constantan	:	6,
		cupronickel	:	6,
		demonmetal	:	6,
		invar	:	6,
		iridium	:	6,
		lockalloy	:	6,
		manganese	:	6,
		platinum	:	6,
		tantalum	:	6,
		thorium	:	6,
		titanium	:	6,
		uranium	:	6,
		alnico	:	7,
		ardite	:	7,
		enderium	:	7,
		obsidiansteel	:	7,
		osmium	:	7,
		signalium	:	7,
		thortanium	:	7,
		titaniumaluminum	:	7,
		titaniumiridium	:	7,
		titiyum	:	7,
		bassalt	:	8,
		hardenedsteel	:	8,
		jaxum	:	8,
		karmesine	:	8,
		manylium	:	8,
		osmiridium	:	8,
		osram	:	8,
		ovium	:	8,
		prometheum	:	8,
		refinedglowstone	:	8,
		tiberium	:	8,
		tungsten	:	8,
		zirconium	:	8,
		baseessence	:	9,
		boron	:	9,
		chromium	:	9,
		nichrome	:	9,
		stainlesssteel	:	9,
		terrax	:	9,
		tritonite	:	9,
		valyrium	:	9,
		ferroboron	:	10,
		ignitz	:	10,
		inferium	:	10,
		triberium	:	10,
		abyssum	:	11,
		aurorum	:	11,
		hardcarbon	:	11,
		meteorite	:	11,
		prudentium	:	11,
		refinedobsidian	:	11,
		toughalloy	:	11,
		astrum	:	12,
		dyonite	:	12,
		eezo	:	12,
		fractum	:	12,
		intermedium	:	12,
		lumix	:	12,
		obsiderite	:	12,
		osglogloss	:	12,
		starsteel	:	12,
		violium	:	12,
		yrdeen	:	12,
		duranite	:	13,
		obsidiorite	:	13,
		proxii	:	13,
		seismum	:	13,
		superium	:	13,
		imperiomite	:	14,
		iox	:	14,
		niob	:	14,
		supremeum	:	14,
		uru	:	14,
		insanium	:	15,
		nihilite	:	15,
		nucleum	:	15,
		solarium	:	15,
		vibranium	:	15,
		adamant	:	16,
		adamantine	:	17,
		adamatine	:	0,
		aeonsteel	:	0,
		alduorite	:	0,
		aluminumbrass	:	0,
		amber	:	0,
		antimony	:	0,
		aquarium	:	0,
		astralsilver	:	0,
		atlarus	:	0,
		awakeddraconium	:	0,
		blackquartz	:	0,
		bloodbronze	:	0,
		bloodinfusediron	:	0,
		carmot	:	0,
		ceruclase	:	0,
		coal	:	0,
		coldiron	:	0,
		crystalized	:	0,
		deepiron	:	0,
		diamantine	:	0,
		diamond	:	0,
		dilithium	:	0,
		dogbearium	:	0,
		draconium	:	0,
		emeradic	:	0,
		emerald	:	0,
		enchantedmetal	:	0,
		enderpearl	:	0,
		enoricrystal	:	0,
		evilinfusedmetal	:	0,
		eximite	:	0,
		fiery	:	0,
		froststeel	:	0,
		glowstone	:	0,
		hslasteel	:	0,
		ignatius	:	0,
		inertbloodiron	:	0,
		infuscolium	:	0,
		ironwood	:	0,
		jade	:	0,
		kalendrite	:	0,
		knightmetal	:	0,
		knightslime	:	0,
		lapis	:	0,
		lemuurite	:	0,
		lumium	:	0,
		lutetium	:	0,
		machalite	:	0,
		maganese	:	0,
		magnite	:	0,
		mercury	:	0,
		meutoite	:	0,
		midasium	:	0,
		mithril	:	0,
		neptunium	:	0,
		netherquartz	:	0,
		obsidian	:	0,
		opal	:	0,
		orichalcum	:	0,
		oureclasce	:	0,
		palis	:	0,
		pandorium	:	0,
		pewter	:	0,
		phosphorite	:	0,
		pigiron	:	0,
		pinkslimeingot	:	0,
		plutonium	:	0,
		potash	:	0,
		prometheum	:	0,
		prometheum	:	0,
		queensgold	:	0,
		redstone	:	0,
		restonia	:	0,
		rubracium	:	0,
		ruby	:	0,
		rutile	:	0,
		saguinite	:	0,
		sapphire	:	0,
		shadowiron	:	0,
		silicon	:	0,
		silicon	:	0,
		siliconcarbide	:	0,
		sinisterium	:	0,
		soulium	:	0,
		spectre	:	0,
		stalmetal	:	0,
		sulphur	:	0,
		tanzanite	:	0,
		topaz	:	0,
		valyriuansteel	:	0,
		vulcanite	:	0,
		vyroxeres	:	0,

	};
