//=====================================================================================================================================================================================================	
//	Removing JEI tabs for disabled components and devices
//=====================================================================================================================================================================================================


mods.jei.JEI.hideCategory("actuallyadditions.crushing");
mods.jei.JEI.hideCategory("mmdlib.crackhammer");
mods.jei.JEI.hideCategory("zmaster587.AR.platePresser");
mods.jei.JEI.hideCategory("xu2_machine_extrautils2:crusher");

/*
--- JEI Categories ---
minecraft.crafting
minecraft.fuel
minecraft.smelting
minecraft.brewing
minecraft.anvil
mctsmelteryio:casting_machine
mctsmelteryio:fuel_controller
techguns.ammopress
techguns.metalpress
techguns.chemlab
techguns.fabricator
techguns.camobench
techguns.chargingstation
techguns.reactionchamber
techguns.oredrill
techguns.blastfurnace
techguns.grinder
techguns.upgradebench
astralsorcery.lightwell
astralsorcery.grindstone
astralsorcery.infuser
astralsorcery.lightTransmutation
astralsorcery.altar.trait
astralsorcery.altar.constellation
astralsorcery.altar.attunement
astralsorcery.altar.discovery
crossroads.grindstone
crossroads.fluid_cooling
crossroads.heating_crucible
crossroads.heat_exchanger
crossroads.detailed_crafter
crossroads.arcane_extractor
crossroads.fusion_beam
crossroads.reaction
crossroads.reag_info
terraqueous.endertable
magneticraft.crushing_table
magneticraft.sluice_box
magneticraft.grinder
magneticraft.sieve
magneticraft.hydraulic_press
magneticraft.oil_heater
magneticraft.refinery
magneticraft.gasification_unit
magneticraft.thermopile
artisanworktables_tailor_workshop
artisanworktables_mason_workshop
artisanworktables_blacksmith_workshop
artisanworktables_basic_workshop
artisanworktables_potter_workshop
it.distiller
it.boiler
it.solarTower
notreepunching.knife
notreepunching.fire_pit
tconstruct.smeltery
tconstruct.alloy
tconstruct.casting_table
tconstruct.dryingrack
actuallyadditions.coffee
actuallyadditions.compost
actuallyadditions.crushing
actuallyadditions.reconstructor
actuallyadditions.empowerer
actuallyadditions.booklet
mekanism.chemicalcrystallizer
mekanism.chemicaldissolutionchamber
mekanism.chemicalinfuser
mekanism.chemicaloxidizer
mekanism.chemicalwasher
mekanism.electrolyticseparator
mekanism.metallurgicinfuser
mekanism.pressurizedreactionchamber
mekanism.rotary_condensentrator_condensentrating
mekanism.rotary_condensentrator_decondensentrating
mekanism.solarneutronactivator
mekanism.combiner
mekanism.purificationchamber
mekanism.osmiumcompressor
mekanism.chemicalinjectionchamber
mekanism.precisionsawmill
mekanism.enrichmentchamber
mekanism.crusher
mekanism.thermalevaporationplant
horsepower.grinding
horsepower.manual_chopping
horsepower.chopping
horsepower.press
horsepower.press_fluid
ie.cokeoven
ie.alloysmelter
ie.blastfurnace
ie.blastfurnace.fuel
ie.metalPress
ie.crusher
ie.workbench
ie.squeezer
ie.fermenter
ie.refinery
ie.arcFurnace
ie.arcFurnace.recycling
ie.bottlingMachine
ie.mixer
Imbuing
tinkersforging.anvil
iceandfire.fire_dragon_forge
iceandfire.ice_dragon_forge
cuisine.chopping_board
cuisine.mortar
cuisine.mill
cuisine.vessel
cuisine.basin_boiling
cuisine.basin_squeezing
cuisine.basin_throwing
cuisine.firepit_fuel
chisel.chiseling
mysticalagradditions:tier_6_crop_jei
rockhounding_oretiers.coal_refiner
rockhounding_oretiers.peat_drier
rockhounding_oretiers.bloomery
botania.brewery
botania.pureDaisy
botania.runicAltar
botania.petals
botania.elvenTrade
botania.manaPool
botania.orechid
botania.orechid_ignem
tcomplement:melter
tcomplement:high_oven_mix
tcomplement:high_oven_heat
tcomplement:high_oven_melting
jei.information
rustic.crushing_tub
rustic.evaporating
rustic.alchemy_advanced
rustic.alchemy_simple
rustic.brewing
zmaster587.AR.rollingMachine
zmaster587.AR.lathe
zmaster587.AR.precisionAssembler
zmaster587.AR.sawMill
zmaster587.AR.chemicalReactor
zmaster587.AR.crystallizer
zmaster587.AR.electrolyzer
zmaster587.AR.arcFurnace
zmaster587.AR.platePresser
zmaster587.AR.centrifuge
extrautils2.blockPatterns
extrautils2.terraformer
extrautils2.resonator
xu2_machine_extrautils2:furnace
xu2_machine_extrautils2:crusher
xu2_machine_extrautils2:enchanter
xu2_machine_extrautils2:generator_survival
xu2_machine_extrautils2:generator
xu2_machine_extrautils2:generator_culinary
xu2_machine_extrautils2:generator_lava
xu2_machine_extrautils2:generator_redstone
xu2_machine_extrautils2:generator_ender
xu2_machine_extrautils2:generator_potion
xu2_machine_extrautils2:generator_pink
xu2_machine_extrautils2:generator_overclock
xu2_machine_extrautils2:generator_tnt
xu2_machine_extrautils2:generator_netherstar
xu2_machine_extrautils2:generator_dragonsbreath
xu2_machine_extrautils2:generator_ice
xu2_machine_extrautils2:generator_death
xu2_machine_extrautils2:generator_enchant
xu2_machine_extrautils2:generator_slime
nuclearcraft_manufactory
nuclearcraft_isotope_separator
nuclearcraft_decay_hastener
nuclearcraft_fuel_reprocessor
nuclearcraft_alloy_furnace
nuclearcraft_infuser
nuclearcraft_melter
nuclearcraft_supercooler
nuclearcraft_electrolyser
nuclearcraft_irradiator
nuclearcraft_ingot_former
nuclearcraft_pressurizer
nuclearcraft_chemical_reactor
nuclearcraft_salt_mixer
nuclearcraft_crystallizer
nuclearcraft_dissolver
nuclearcraft_extractor
nuclearcraft_centrifuge
nuclearcraft_rock_crusher
nuclearcraft_collector
nuclearcraft_active_cooler
nuclearcraft_decay_generator
nuclearcraft_fission
nuclearcraft_fusion
nuclearcraft_salt_fission
nuclearcraft_coolant_heater
nuclearcraft_heat_exchanger
nuclearcraft_high_turbine
nuclearcraft_condenser


*/