//=====================================================================================================================================================================================================	
//	Global variables are defined here for use in other scripts.
//=====================================================================================================================================================================================================	


//=====================================================================================================================================================================================================	
//These imports must be included to cast the arrays
//=====================================================================================================================================================================================================	


#priority 9999

import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.oredict.IOreDict;
import crafttweaker.liquid.ILiquidStack;


//=====================================================================================================================================================================================================	
//	Fluid Tables Liquids must actually be loaded in the game, otherwise script will error
//=====================================================================================================================================================================================================


		//	Molten Metals _______________________________________________________________________________________________________________________________________________________________________
	global GlobalMoltenMetal as ILiquidStack[string] = {
		Copshowium				:	<liquid:copshowium>,
		Copper					:	<liquid:copper>,
		Lead					:	<liquid:lead>,
		Lithium					:	<liquid:lithium>,
		Tin						:	<liquid:tin>,
		Bronze					:	<liquid:bronze>,
		Cadmium					:	<liquid:cadmium>,
		Gold					:	<liquid:gold>,
		Magnesium				:	<liquid:magnesium>,
		Molybdochalkos			:	<liquid:molybdochalkos>,
		Cerrosafe				:	<liquid:cerrosafe>,
		Magmolybdochalkosmuth	:	<liquid:magmolybdochalkosmuth>,
		Silver					:	<liquid:silver>,
		Zinc					:	<liquid:zinc>,
		Aluminum				:	<liquid:aluminum>,
		Brass					:	<liquid:brass>,
		Electrum				:	<liquid:electrum>,
		Iron					:	<liquid:iron>,
		Galvanizedsteel			:	<liquid:galvanizedsteel>,
		Nickel					:	<liquid:nickel>,
		Palladium				:	<liquid:palladium_fluid>,
		Steel					:	<liquid:steel>,
		Alumite					:	<liquid:alumite>,
		Cobalt					:	<liquid:cobalt>,
		Constantan				:	<liquid:constantan>,
		Demonmetal				:	<liquid:xu_demonic_metal>,
		Invar					:	<liquid:invar>,
		Iridium					:	<liquid:iridium>,
		Manganese				:	<liquid:manganese>,
		Platinum				:	<liquid:platinum>,
		Thorium					:	<liquid:thorium>,
		Titanium				:	<liquid:titanium>,
		Uranium					:	<liquid:uranium>,
		Alnico					:	<liquid:alnico>,
		Ardite					:	<liquid:ardite>,
		Enderium				:	<liquid:enderium>,
		Osmium					:	<liquid:osmium>,
		Signalum				:	<liquid:signalum>,
		Thortanium				:	<liquid:thortanium>,
		Titaniumaluminum		:	<liquid:titaniumaluminide>,
		Titaniumiridium			:	<liquid:titaniumiridium>,
		Hardenedsteel			:	<liquid:hardenedsteel>,
		Jauxum					:	<liquid:jauxum_fluid>,
		Karmesine				:	<liquid:karmesine_fluid>,
		Manyullyn				:	<liquid:manyullyn>,
		Osmiridium				:	<liquid:osmiridium>,
		Osram					:	<liquid:osram_fluid>,
		Ovium					:	<liquid:ovium_fluid>,
		Prometheum				:	<liquid:prometheum_fluid>,
		Refinedglowstone		:	<liquid:refinedglowstone>,
		Tiberium				:	<liquid:tiberium_fluid>,
		Tungsten				:	<liquid:tungsten>,
		Boron					:	<liquid:boron>,
		Chromium				:	<liquid:chromium>,
		Nichrome				:	<liquid:nichrome>,
		Stainlesssteel			:	<liquid:stainlesssteel>,
		Terrax					:	<liquid:terrax_fluid>,
		Tritonite				:	<liquid:tritonite_fluid>,
		Valyrium				:	<liquid:valyrium_fluid>,
		Ferroboron				:	<liquid:ferroboron>,
		Ignitz					:	<liquid:ignitz_fluid>,
		Triberium				:	<liquid:triberium_fluid>,
		Abyssum					:	<liquid:abyssum_fluid>,
		Aurorium				:	<liquid:aurorium_fluid>,
		Hardcarbon				:	<liquid:hard_carbon>,
		Meteorite				:	<liquid:meteorite_fluid>,
		Refinedobsidian			:	<liquid:refinedobsidian>,
		Toughalloy				:	<liquid:tough>,
		Astrium					:	<liquid:astrium_fluid>,
		Dyonite					:	<liquid:dyonite_fluid>,
		Eezo					:	<liquid:eezo_fluid>,
		Fractum					:	<liquid:fractum_fluid>,
		Lumix					:	<liquid:lumix_fluid>,
		Obsidiorite				:	<liquid:obsidiorite_fluid>,
		Osgloglas				:	<liquid:osgloglas>,
		Violium					:	<liquid:violium_fluid>,
		Yrdeen					:	<liquid:yrdeen_fluid>,
		Duranite				:	<liquid:duranite_fluid>,
		Obsidiorite				:	<liquid:obsidiorite_fluid>,
		Proxii					:	<liquid:proxii_fluid>,
		Seismum					:	<liquid:seismum_fluid>,
		Imperomite				:	<liquid:imperomite_fluid>,
		Iox						:	<liquid:iox_fluid>,
		Niob					:	<liquid:niob_fluid>,
		Uru						:	<liquid:uru_fluid>,
		Nihilite				:	<liquid:nihilite_fluid>,
		Nucleum					:	<liquid:nucleum_fluid>,
		Solarium				:	<liquid:solarium_fluid>,
		Vibranium				:	<liquid:vibranium_fluid>,
		Adamant					:	<liquid:adamant_fluid>,
		Aluminumbrass			:	<liquid:alubrass>,
		Bloodbronze				:	<liquid:bloodbronze>,
		Bloodinfusediron		:	<liquid:molten_blood_infused_iron>,
		Dilithium				:	<liquid:dilithium_fluid>,
		Enchantedmetal			:	<liquid:xu_enchanted_metal>,
		Evilinfusedmetal		:	<liquid:xu_evil_metal>,
		Glowstone				:	<liquid:glowstone>,
		Hslasteel				:	<liquid:hslasteel>,
		Knightslime				:	<liquid:knightslime>,
		Lumium					:	<liquid:lumium>,
		Redstone				:	<liquid:redstone>,
	};
		//	Leeched Metal Solution	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalLeechedMetalSolution as ILiquidStack[string] = {
		"Copper"		:	<liquid:copper_leeched_metal_solution>,
		"Gold"			:	<liquid:gold_leeched_metal_solution>,
		"Lead"			:	<liquid:lead_leeched_metal_solution>,
		"Lithium"		:	<liquid:lithium_leeched_metal_solution>,
		"Tin"			:	<liquid:tin_leeched_metal_solution>,
		"Magnesium"		:	<liquid:magnesium_leeched_metal_solution>,
		"Silver"		:	<liquid:silver_leeched_metal_solution>,
		"Zinc"			:	<liquid:zinc_leeched_metal_solution>,
		"Aluminum"		:	<liquid:aluminum_leeched_metal_solution>,
		"Iron"			:	<liquid:iron_leeched_metal_solution>,
		"Palladium"		:	<liquid:palladium_leeched_metal_solution>,
		"Cobalt"		:	<liquid:cobalt_leeched_metal_solution>,
		"Magnite"		:	<liquid:magnite_leeched_metal_solution>,
		"Manganese"		:	<liquid:manganese_leeched_metal_solution>,
		"Nickel"		:	<liquid:nickel_leeched_metal_solution>,
		"Thorium"		:	<liquid:thorium_leeched_metal_solution>,
		"Titanium"		:	<liquid:titanium_leeched_metal_solution>,
		"Uranium"		:	<liquid:uranium_leeched_metal_solution>,
		"Ardite"		:	<liquid:ardite_leeched_metal_solution>,
		"Osmium"		:	<liquid:osmium_leeched_metal_solution>,
		"Platinum"		:	<liquid:platinum_leeched_metal_solution>,
		"Iridium"		:	<liquid:iridium_leeched_metal_solution>,
		"Jauxum"		:	<liquid:jauxum_leeched_metal_solution>,
		"Karmesine"		:	<liquid:karmesine_leeched_metal_solution>,
		"Osram"			:	<liquid:osram_leeched_metal_solution>,
		"Ovium"			:	<liquid:ovium_leeched_metal_solution>,
		"Prometheum"	:	<liquid:prometheum_leeched_metal_solution>,
		"Tiberium"		:	<liquid:tiberium_leeched_metal_solution>,
		"Tungsten"		:	<liquid:tungsten_leeched_metal_solution>,
		"Zirconium"		:	<liquid:zirconium_leeched_metal_solution>,
		"Boron"			:	<liquid:boron_leeched_metal_solution>,
		"Chromium"		:	<liquid:chromium_leeched_metal_solution>,
		"Valyrium"		:	<liquid:valyrium_leeched_metal_solution>,
		"Mithril"		:	<liquid:mithril_leeched_metal_solution>,
		"Abyssum"		:	<liquid:abyssum_leeched_metal_solution>,
		"Aurorium"		:	<liquid:aurorium_leeched_metal_solution>,
		"Meteorite"		:	<liquid:meteorite_leeched_metal_solution>,
		"Eezo"			:	<liquid:eezo_leeched_metal_solution>,
		"Duranite"		:	<liquid:duranite_leeched_metal_solution>,
		"Vibranium"		:	<liquid:vibranium_leeched_metal_solution>,
	};
		//	More Leeched Metal Solution	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalMoreLeechedMetalSolution as ILiquidStack[string] = {
		"Copper"		:	<liquid:copper_more_leeched_metal_solution>,
		"Gold"			:	<liquid:gold_more_leeched_metal_solution>,
		"Lead"			:	<liquid:lead_more_leeched_metal_solution>,
		"Lithium"		:	<liquid:lithium_more_leeched_metal_solution>,
		"Tin"			:	<liquid:tin_more_leeched_metal_solution>,
		"Magnesium"		:	<liquid:magnesium_more_leeched_metal_solution>,
		"Silver"		:	<liquid:silver_more_leeched_metal_solution>,
		"Zinc"			:	<liquid:zinc_more_leeched_metal_solution>,
		"Aluminum"		:	<liquid:aluminum_more_leeched_metal_solution>,
		"Iron"			:	<liquid:iron_more_leeched_metal_solution>,
		"Palladium"		:	<liquid:palladium_more_leeched_metal_solution>,
		"Cobalt"		:	<liquid:cobalt_more_leeched_metal_solution>,
		"Magnite"		:	<liquid:magnite_more_leeched_metal_solution>,
		"Manganese"		:	<liquid:manganese_more_leeched_metal_solution>,
		"Nickel"		:	<liquid:nickel_more_leeched_metal_solution>,
		"Thorium"		:	<liquid:thorium_more_leeched_metal_solution>,
		"Titanium"		:	<liquid:titanium_more_leeched_metal_solution>,
		"Uranium"		:	<liquid:uranium_more_leeched_metal_solution>,
		"Ardite"		:	<liquid:ardite_more_leeched_metal_solution>,
		"Osmium"		:	<liquid:osmium_more_leeched_metal_solution>,
		"Platinum"		:	<liquid:platinum_more_leeched_metal_solution>,
		"Iridium"		:	<liquid:iridium_more_leeched_metal_solution>,
		"Jauxum"		:	<liquid:jauxum_more_leeched_metal_solution>,
		"Karmesine"		:	<liquid:karmesine_more_leeched_metal_solution>,
		"Osram"			:	<liquid:osram_more_leeched_metal_solution>,
		"Ovium"			:	<liquid:ovium_more_leeched_metal_solution>,
		"Prometheum"	:	<liquid:prometheum_more_leeched_metal_solution>,
		"Tiberium"		:	<liquid:tiberium_more_leeched_metal_solution>,
		"Tungsten"		:	<liquid:tungsten_more_leeched_metal_solution>,
		"Zirconium"		:	<liquid:zirconium_more_leeched_metal_solution>,
		"Boron"			:	<liquid:boron_more_leeched_metal_solution>,
		"Chromium"		:	<liquid:chromium_more_leeched_metal_solution>,
		"Valyrium"		:	<liquid:valyrium_more_leeched_metal_solution>,
		"Mithril"		:	<liquid:mithril_more_leeched_metal_solution>,
		"Abyssum"		:	<liquid:abyssum_more_leeched_metal_solution>,
		"Aurorium"		:	<liquid:aurorium_more_leeched_metal_solution>,
		"Meteorite"		:	<liquid:meteorite_more_leeched_metal_solution>,
		"Eezo"			:	<liquid:eezo_more_leeched_metal_solution>,
		"Duranite"		:	<liquid:duranite_more_leeched_metal_solution>,
		"Vibranium"		:	<liquid:vibranium_more_leeched_metal_solution>,
	};
		//	Heated Metal Solution	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalHeatedMetalSolution as ILiquidStack[string] = {
		"Copper"		:	<liquid:copper_heated_metal_solution>,
		"Gold"			:	<liquid:gold_heated_metal_solution>,
		"Lead"			:	<liquid:lead_heated_metal_solution>,
		"Lithium"		:	<liquid:lithium_heated_metal_solution>,
		"Tin"			:	<liquid:tin_heated_metal_solution>,
		"Magnesium"		:	<liquid:magnesium_heated_metal_solution>,
		"Silver"		:	<liquid:silver_heated_metal_solution>,
		"Zinc"			:	<liquid:zinc_heated_metal_solution>,
		"Aluminum"		:	<liquid:aluminum_heated_metal_solution>,
		"Iron"			:	<liquid:iron_heated_metal_solution>,
		"Palladium"		:	<liquid:palladium_heated_metal_solution>,
		"Cobalt"		:	<liquid:cobalt_heated_metal_solution>,
		"Magnite"		:	<liquid:magnite_heated_metal_solution>,
		"Manganese"		:	<liquid:manganese_heated_metal_solution>,
		"Nickel"		:	<liquid:nickel_heated_metal_solution>,
		"Thorium"		:	<liquid:thorium_heated_metal_solution>,
		"Titanium"		:	<liquid:titanium_heated_metal_solution>,
		"Uranium"		:	<liquid:uranium_heated_metal_solution>,
		"Ardite"		:	<liquid:ardite_heated_metal_solution>,
		"Osmium"		:	<liquid:osmium_heated_metal_solution>,
		"Platinum"		:	<liquid:platinum_heated_metal_solution>,
		"Iridium"		:	<liquid:iridium_heated_metal_solution>,
		"Jauxum"		:	<liquid:jauxum_heated_metal_solution>,
		"Karmesine"		:	<liquid:karmesine_heated_metal_solution>,
		"Osram"			:	<liquid:osram_heated_metal_solution>,
		"Ovium"			:	<liquid:ovium_heated_metal_solution>,
		"Prometheum"	:	<liquid:prometheum_heated_metal_solution>,
		"Tiberium"		:	<liquid:tiberium_heated_metal_solution>,
		"Tungsten"		:	<liquid:tungsten_heated_metal_solution>,
		"Zirconium"		:	<liquid:zirconium_heated_metal_solution>,
		"Boron"			:	<liquid:boron_heated_metal_solution>,
		"Chromium"		:	<liquid:chromium_heated_metal_solution>,
		"Valyrium"		:	<liquid:valyrium_heated_metal_solution>,
		"Mithril"		:	<liquid:mithril_heated_metal_solution>,
		"Abyssum"		:	<liquid:abyssum_heated_metal_solution>,
		"Aurorium"		:	<liquid:aurorium_heated_metal_solution>,
		"Meteorite"		:	<liquid:meteorite_heated_metal_solution>,
		"Eezo"			:	<liquid:eezo_heated_metal_solution>,
		"Duranite"		:	<liquid:duranite_heated_metal_solution>,
		"Vibranium"		:	<liquid:vibranium_heated_metal_solution>,
	};
		//	Refined Metal Solution	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalRefinedMetalSolution as ILiquidStack[string] = {
		"Copper"		:	<liquid:copper_refined_metal_solution>,
		"Gold"			:	<liquid:gold_refined_metal_solution>,
		"Lead"			:	<liquid:lead_refined_metal_solution>,
		"Lithium"		:	<liquid:lithium_refined_metal_solution>,
		"Tin"			:	<liquid:tin_refined_metal_solution>,
		"Magnesium"		:	<liquid:magnesium_refined_metal_solution>,
		"Silver"		:	<liquid:silver_refined_metal_solution>,
		"Zinc"			:	<liquid:zinc_refined_metal_solution>,
		"Aluminum"		:	<liquid:aluminum_refined_metal_solution>,
		"Iron"			:	<liquid:iron_refined_metal_solution>,
		"Palladium"		:	<liquid:palladium_refined_metal_solution>,
		"Cobalt"		:	<liquid:cobalt_refined_metal_solution>,
		"Magnite"		:	<liquid:magnite_refined_metal_solution>,
		"Manganese"		:	<liquid:manganese_refined_metal_solution>,
		"Nickel"		:	<liquid:nickel_refined_metal_solution>,
		"Thorium"		:	<liquid:thorium_refined_metal_solution>,
		"Titanium"		:	<liquid:titanium_refined_metal_solution>,
		"Uranium"		:	<liquid:uranium_refined_metal_solution>,
		"Ardite"		:	<liquid:ardite_refined_metal_solution>,
		"Osmium"		:	<liquid:osmium_refined_metal_solution>,
		"Platinum"		:	<liquid:platinum_refined_metal_solution>,
		"Iridium"		:	<liquid:iridium_refined_metal_solution>,
		"Jauxum"		:	<liquid:jauxum_refined_metal_solution>,
		"Karmesine"		:	<liquid:karmesine_refined_metal_solution>,
		"Osram"			:	<liquid:osram_refined_metal_solution>,
		"Ovium"			:	<liquid:ovium_refined_metal_solution>,
		"Prometheum"	:	<liquid:prometheum_refined_metal_solution>,
		"Tiberium"		:	<liquid:tiberium_refined_metal_solution>,
		"Tungsten"		:	<liquid:tungsten_refined_metal_solution>,
		"Zirconium"		:	<liquid:zirconium_refined_metal_solution>,
		"Boron"			:	<liquid:boron_refined_metal_solution>,
		"Chromium"		:	<liquid:chromium_refined_metal_solution>,
		"Valyrium"		:	<liquid:valyrium_refined_metal_solution>,
		"Mithril"		:	<liquid:mithril_refined_metal_solution>,
		"Abyssum"		:	<liquid:abyssum_refined_metal_solution>,
		"Aurorium"		:	<liquid:aurorium_refined_metal_solution>,
		"Meteorite"		:	<liquid:meteorite_refined_metal_solution>,
		"Eezo"			:	<liquid:eezo_refined_metal_solution>,
		"Duranite"		:	<liquid:duranite_refined_metal_solution>,
		"Vibranium"		:	<liquid:vibranium_refined_metal_solution>,
	};
		//	Sludge Metal Solution	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalSludgeMetalSolution as ILiquidStack[string] = {
		"Copper"		:	<liquid:copper_sludge_metal_solution>,
		"Gold"			:	<liquid:gold_sludge_metal_solution>,
		"Lead"			:	<liquid:lead_sludge_metal_solution>,
		"Lithium"		:	<liquid:lithium_sludge_metal_solution>,
		"Tin"			:	<liquid:tin_sludge_metal_solution>,
		"Magnesium"		:	<liquid:magnesium_sludge_metal_solution>,
		"Silver"		:	<liquid:silver_sludge_metal_solution>,
		"Zinc"			:	<liquid:zinc_sludge_metal_solution>,
		"Aluminum"		:	<liquid:aluminum_sludge_metal_solution>,
		"Iron"			:	<liquid:iron_sludge_metal_solution>,
		"Palladium"		:	<liquid:palladium_sludge_metal_solution>,
		"Cobalt"		:	<liquid:cobalt_sludge_metal_solution>,
		"Magnite"		:	<liquid:magnite_sludge_metal_solution>,
		"Manganese"		:	<liquid:manganese_sludge_metal_solution>,
		"Nickel"		:	<liquid:nickel_sludge_metal_solution>,
		"Thorium"		:	<liquid:thorium_sludge_metal_solution>,
		"Titanium"		:	<liquid:titanium_sludge_metal_solution>,
		"Uranium"		:	<liquid:uranium_sludge_metal_solution>,
		"Ardite"		:	<liquid:ardite_sludge_metal_solution>,
		"Osmium"		:	<liquid:osmium_sludge_metal_solution>,
		"Platinum"		:	<liquid:platinum_sludge_metal_solution>,
		"Iridium"		:	<liquid:iridium_sludge_metal_solution>,
		"Jauxum"		:	<liquid:jauxum_sludge_metal_solution>,
		"Karmesine"		:	<liquid:karmesine_sludge_metal_solution>,
		"Osram"			:	<liquid:osram_sludge_metal_solution>,
		"Ovium"			:	<liquid:ovium_sludge_metal_solution>,
		"Prometheum"	:	<liquid:prometheum_sludge_metal_solution>,
		"Tiberium"		:	<liquid:tiberium_sludge_metal_solution>,
		"Tungsten"		:	<liquid:tungsten_sludge_metal_solution>,
		"Zirconium"		:	<liquid:zirconium_sludge_metal_solution>,
		"Boron"			:	<liquid:boron_sludge_metal_solution>,
		"Chromium"		:	<liquid:chromium_sludge_metal_solution>,
		"Valyrium"		:	<liquid:valyrium_sludge_metal_solution>,
		"Mithril"		:	<liquid:mithril_sludge_metal_solution>,
		"Abyssum"		:	<liquid:abyssum_sludge_metal_solution>,
		"Aurorium"		:	<liquid:aurorium_sludge_metal_solution>,
		"Meteorite"		:	<liquid:meteorite_sludge_metal_solution>,
		"Eezo"			:	<liquid:eezo_sludge_metal_solution>,
		"Duranite"		:	<liquid:duranite_sludge_metal_solution>,
		"Vibranium"		:	<liquid:vibranium_sludge_metal_solution>,
	};
		//	Clean Metal Solution	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalCleanMetalSolution as ILiquidStack[string] = {
		"Copper"		:	<liquid:copper_clean_metal_solution>,
		"Gold"			:	<liquid:gold_clean_metal_solution>,
		"Lead"			:	<liquid:lead_clean_metal_solution>,
		"Lithium"		:	<liquid:lithium_clean_metal_solution>,
		"Tin"			:	<liquid:tin_clean_metal_solution>,
		"Magnesium"		:	<liquid:magnesium_clean_metal_solution>,
		"Silver"		:	<liquid:silver_clean_metal_solution>,
		"Zinc"			:	<liquid:zinc_clean_metal_solution>,
		"Aluminum"		:	<liquid:aluminum_clean_metal_solution>,
		"Iron"			:	<liquid:iron_clean_metal_solution>,
		"Palladium"		:	<liquid:palladium_clean_metal_solution>,
		"Cobalt"		:	<liquid:cobalt_clean_metal_solution>,
		"Magnite"		:	<liquid:magnite_clean_metal_solution>,
		"Manganese"		:	<liquid:manganese_clean_metal_solution>,
		"Nickel"		:	<liquid:nickel_clean_metal_solution>,
		"Thorium"		:	<liquid:thorium_clean_metal_solution>,
		"Titanium"		:	<liquid:titanium_clean_metal_solution>,
		"Uranium"		:	<liquid:uranium_clean_metal_solution>,
		"Ardite"		:	<liquid:ardite_clean_metal_solution>,
		"Osmium"		:	<liquid:osmium_clean_metal_solution>,
		"Platinum"		:	<liquid:platinum_clean_metal_solution>,
		"Iridium"		:	<liquid:iridium_clean_metal_solution>,
		"Jauxum"		:	<liquid:jauxum_clean_metal_solution>,
		"Karmesine"		:	<liquid:karmesine_clean_metal_solution>,
		"Osram"			:	<liquid:osram_clean_metal_solution>,
		"Ovium"			:	<liquid:ovium_clean_metal_solution>,
		"Prometheum"	:	<liquid:prometheum_clean_metal_solution>,
		"Tiberium"		:	<liquid:tiberium_clean_metal_solution>,
		"Tungsten"		:	<liquid:tungsten_clean_metal_solution>,
		"Zirconium"		:	<liquid:zirconium_clean_metal_solution>,
		"Boron"			:	<liquid:boron_clean_metal_solution>,
		"Chromium"		:	<liquid:chromium_clean_metal_solution>,
		"Valyrium"		:	<liquid:valyrium_clean_metal_solution>,
		"Mithril"		:	<liquid:mithril_clean_metal_solution>,
		"Abyssum"		:	<liquid:abyssum_clean_metal_solution>,
		"Aurorium"		:	<liquid:aurorium_clean_metal_solution>,
		"Meteorite"		:	<liquid:meteorite_clean_metal_solution>,
		"Eezo"			:	<liquid:eezo_clean_metal_solution>,
		"Duranite"		:	<liquid:duranite_clean_metal_solution>,
		"Vibranium"		:	<liquid:vibranium_clean_metal_solution>,
	};
		//	Distillate	_______________________________________________________________________________________________________________________________________________________________________
	global GlobalDistillate as ILiquidStack[string] = {
		"Copper"		:	<liquid:copper_distillate>,
		"Gold"			:	<liquid:gold_distillate>,
		"Lead"			:	<liquid:lead_distillate>,
		"Lithium"		:	<liquid:lithium_distillate>,
		"Tin"			:	<liquid:tin_distillate>,
		"Magnesium"		:	<liquid:magnesium_distillate>,
		"Silver"		:	<liquid:silver_distillate>,
		"Zinc"			:	<liquid:zinc_distillate>,
		"Aluminum"		:	<liquid:aluminum_distillate>,
		"Iron"			:	<liquid:iron_distillate>,
		"Palladium"		:	<liquid:palladium_distillate>,
		"Cobalt"		:	<liquid:cobalt_distillate>,
		"Magnite"		:	<liquid:magnite_distillate>,
		"Manganese"		:	<liquid:manganese_distillate>,
		"Nickel"		:	<liquid:nickel_distillate>,
		"Thorium"		:	<liquid:thorium_distillate>,
		"Titanium"		:	<liquid:titanium_distillate>,
		"Uranium"		:	<liquid:uranium_distillate>,
		"Ardite"		:	<liquid:ardite_distillate>,
		"Osmium"		:	<liquid:osmium_distillate>,
		"Platinum"		:	<liquid:platinum_distillate>,
		"Iridium"		:	<liquid:iridium_distillate>,
		"Jauxum"		:	<liquid:jauxum_distillate>,
		"Karmesine"		:	<liquid:karmesine_distillate>,
		"Osram"			:	<liquid:osram_distillate>,
		"Ovium"			:	<liquid:ovium_distillate>,
		"Prometheum"	:	<liquid:prometheum_distillate>,
		"Tiberium"		:	<liquid:tiberium_distillate>,
		"Tungsten"		:	<liquid:tungsten_distillate>,
		"Zirconium"		:	<liquid:zirconium_distillate>,
		"Boron"			:	<liquid:boron_distillate>,
		"Chromium"		:	<liquid:chromium_distillate>,
		"Valyrium"		:	<liquid:valyrium_distillate>,
		"Mithril"		:	<liquid:mithril_distillate>,
		"Abyssum"		:	<liquid:abyssum_distillate>,
		"Aurorium"		:	<liquid:aurorium_distillate>,
		"Meteorite"		:	<liquid:meteorite_distillate>,
		"Eezo"			:	<liquid:eezo_distillate>,
		"Duranite"		:	<liquid:duranite_distillate>,
		"Vibranium"		:	<liquid:vibranium_distillate>,
	};