#norun
//=====================================================================================================================================================================================================	
//This script is a template to be copied into other scripts that need the dynamic mappings.  If Zenscript wasn't a steaming pile of ass, I could simply reference these variables from other scripts without having to copy them to all the other scripts, but NOOOO, trying to do that just doesn't work.
//=====================================================================================================================================================================================================	


//=====================================================================================================================================================================================================	
//These imports must be included to cast the arrays
//=====================================================================================================================================================================================================	


import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.oredict.IOreDict;


//=====================================================================================================================================================================================================	
//	Creating Hashtables for all materials and their item forms.
//=====================================================================================================================================================================================================
 //These guys can be called like so:
 //Ingot["Iron"] = <ore:ingotIron>
 //Nugget["Copper"] = <ore:nuggetCopper>
 //Returns an oredict item, so you can: Nugget["Copper"].firstItem


//	Ore Chunks	_______________________________________________________________________________________________________________________________________________________________________
val OreChunk = {
	Iron : <ore:oreChunkIron>,
	Gold : <ore:oreChunkGold>,
	Copper : <ore:oreChunkCopper>,
	Lead : <ore:oreChunkLead>,
	Cobalt : <ore:oreChunkCobalt>,
	Tungsten : <ore:oreChunkTungsten>,
	Aluminum : <ore:oreChunkAluminum>,
	Mithril : <ore:oreChunkMithril>,
	Nickel : <ore:oreChunkNickel>,
	Osmium : <ore:oreChunkOsmium>,
	Silver : <ore:oreChunkSilver>,
	Tin : <ore:oreChunkTin>,
	Zinc : <ore:oreChunkZinc>,
	antimony : <ore:oreChunkAntimony>,
	ardite : <ore:oreChunkArdite>,
	beryllium : <ore:oreChunkBeryllium>,
	bismuth : <ore:oreChunkBismuth>,
	boron : <ore:oreChunkBoron>,
	cadmium : <ore:oreChunkCadmium>,
	chromium : <ore:oreChunkChromium>,
	coldiron : <ore:oreChunkColdiron>,
	dilithium : <ore:oreChunkDilithium>,
	iridium : <ore:oreChunkIridium>,
	lithium : <ore:oreChunkLithium>,
	magnesium : <ore:oreChunkMagnesium>,
	manganese : <ore:oreChunkManganese>,
	mercury : <ore:oreChunkMercury>,
	platinum : <ore:oreChunkPlatinum>,
	plutonium : <ore:oreChunkPlutonium>,
	rutile : <ore:oreChunkRutile>,
	starsteel : <ore:oreChunkStarsteel>,
	tantalum : <ore:oreChunkTantalum>,
	thorium : <ore:oreChunkThorium>,
	titanium : <ore:oreChunkTitanium>,
	uranium : <ore:oreChunkUranium>,
	zirconium : <ore:oreChunkZirconium>,
} as IOreDictEntry[string];

//	Ingots	_______________________________________________________________________________________________________________________________________________________________________
val Ingot = {
	Iron : <ore:ingotIron>,
	Gold : <ore:ingotGold>,
	Copper : <ore:ingotCopper>,
	Lead : <ore:ingotLead>,
	Cobalt : <ore:ingotCobalt>,
	Tungsten : <ore:ingotTungsten>,
	Aluminum : <ore:ingotAluminum>,
	Mithril : <ore:ingotMithril>,
	Nickel : <ore:ingotNickel>,
	Osmium : <ore:ingotOsmium>,
	Silver : <ore:ingotSilver>,
	Tin : <ore:ingotTin>,
	Zinc : <ore:ingotZinc>,
	antimony : <ore:ingotAntimony>,
	ardite : <ore:ingotArdite>,
	beryllium : <ore:ingotBeryllium>,
	bismuth : <ore:ingotBismuth>,
	boron : <ore:ingotBoron>,
	cadmium : <ore:ingotCadmium>,
	chromium : <ore:ingotChromium>,
	coldiron : <ore:ingotColdiron>,
	dilithium : <ore:ingotDilithium>,
	iridium : <ore:ingotIridium>,
	lithium : <ore:ingotLithium>,
	magnesium : <ore:ingotMagnesium>,
	manganese : <ore:ingotManganese>,
	mercury : <ore:ingotMercury>,
	platinum : <ore:ingotPlatinum>,
	plutonium : <ore:ingotPlutonium>,
	rutile : <ore:ingotRutile>,
	starsteel : <ore:ingotStarsteel>,
	tantalum : <ore:ingotTantalum>,
	thorium : <ore:ingotThorium>,
	titanium : <ore:ingotTitanium>,
	uranium : <ore:ingotUranium>,
	zirconium : <ore:ingotZirconium>,
} as IOreDictEntry[string];

//	Blocks	_______________________________________________________________________________________________________________________________________________________________________
val Block = {
	Iron : <ore:blockIron>,
	Gold : <ore:blockGold>,
	Copper : <ore:blockCopper>,
	Lead : <ore:blockLead>,
	Cobalt : <ore:blockCobalt>,
	Tungsten : <ore:blockTungsten>,
	Aluminum : <ore:blockAluminum>,
	Mithril : <ore:blockMithril>,
	Nickel : <ore:blockNickel>,
	Osmium : <ore:blockOsmium>,
	Silver : <ore:blockSilver>,
	Tin : <ore:blockTin>,
	Zinc : <ore:blockZinc>,
	antimony : <ore:blockAntimony>,
	ardite : <ore:blockArdite>,
	beryllium : <ore:blockBeryllium>,
	bismuth : <ore:blockBismuth>,
	boron : <ore:blockBoron>,
	cadmium : <ore:blockCadmium>,
	chromium : <ore:blockChromium>,
	coldiron : <ore:blockColdiron>,
	dilithium : <ore:blockDilithium>,
	iridium : <ore:blockIridium>,
	lithium : <ore:blockLithium>,
	magnesium : <ore:blockMagnesium>,
	manganese : <ore:blockManganese>,
	mercury : <ore:blockMercury>,
	platinum : <ore:blockPlatinum>,
	plutonium : <ore:blockPlutonium>,
	rutile : <ore:blockRutile>,
	starsteel : <ore:blockStarsteel>,
	tantalum : <ore:blockTantalum>,
	thorium : <ore:blockThorium>,
	titanium : <ore:blockTitanium>,
	uranium : <ore:blockUranium>,
	zirconium : <ore:blockZirconium>,
} as IOreDictEntry[string];

//	Nuggets	_______________________________________________________________________________________________________________________________________________________________________
val Nugget = {
	Iron : <ore:nuggetIron>,
	Gold : <ore:nuggetGold>,
	Copper : <ore:nuggetCopper>,
	Lead : <ore:nuggetLead>,
	Cobalt : <ore:nuggetCobalt>,
	Tungsten : <ore:nuggetTungsten>,
	Aluminum : <ore:nuggetAluminum>,
	Mithril : <ore:nuggetMithril>,
	Nickel : <ore:nuggetNickel>,
	Osmium : <ore:nuggetOsmium>,
	Silver : <ore:nuggetSilver>,
	Tin : <ore:nuggetTin>,
	Zinc : <ore:nuggetZinc>,
	antimony : <ore:nuggetAntimony>,
	ardite : <ore:nuggetArdite>,
	beryllium : <ore:nuggetBeryllium>,
	bismuth : <ore:nuggetBismuth>,
	boron : <ore:nuggetBoron>,
	cadmium : <ore:nuggetCadmium>,
	chromium : <ore:nuggetChromium>,
	coldiron : <ore:nuggetColdiron>,
	dilithium : <ore:nuggetDilithium>,
	iridium : <ore:nuggetIridium>,
	lithium : <ore:nuggetLithium>,
	magnesium : <ore:nuggetMagnesium>,
	manganese : <ore:nuggetManganese>,
	mercury : <ore:nuggetMercury>,
	platinum : <ore:nuggetPlatinum>,
	plutonium : <ore:nuggetPlutonium>,
	rutile : <ore:nuggetRutile>,
	starsteel : <ore:nuggetStarsteel>,
	tantalum : <ore:nuggetTantalum>,
	thorium : <ore:nuggetThorium>,
	titanium : <ore:nuggetTitanium>,
	uranium : <ore:nuggetUranium>,
	zirconium : <ore:nuggetZirconium>,
} as IOreDictEntry[string];

//	Magneticraft Chunks	_______________________________________________________________________________________________________________________________________________________________________
val Chunk = {
	Iron : <ore:chunkIron>,
	Gold : <ore:chunkGold>,
	Copper : <ore:chunkCopper>,
	Lead : <ore:chunkLead>,
	Cobalt : <ore:chunkCobalt>,
	Tungsten : <ore:chunkTungsten>,
	Aluminum : <ore:chunkAluminum>,
	Mithril : <ore:chunkMithril>,
	Nickel : <ore:chunkNickel>,
	Osmium : <ore:chunkOsmium>,
	Silver : <ore:chunkSilver>,
	Tin : <ore:chunkTin>,
	Zinc : <ore:chunkZinc>,
	antimony : <ore:chunkAntimony>,
	ardite : <ore:chunkArdite>,
	beryllium : <ore:chunkBeryllium>,
	bismuth : <ore:chunkBismuth>,
	boron : <ore:chunkBoron>,
	cadmium : <ore:chunkCadmium>,
	chromium : <ore:chunkChromium>,
	coldiron : <ore:chunkColdiron>,
	dilithium : <ore:chunkDilithium>,
	iridium : <ore:chunkIridium>,
	lithium : <ore:chunkLithium>,
	magnesium : <ore:chunkMagnesium>,
	manganese : <ore:chunkManganese>,
	mercury : <ore:chunkMercury>,
	platinum : <ore:chunkPlatinum>,
	plutonium : <ore:chunkPlutonium>,
	rutile : <ore:chunkRutile>,
	starsteel : <ore:chunkStarsteel>,
	tantalum : <ore:chunkTantalum>,
	thorium : <ore:chunkThorium>,
	titanium : <ore:chunkTitanium>,
	uranium : <ore:chunkUranium>,
	zirconium : <ore:chunkZirconium>,
} as IOreDictEntry[string];

//	Magneticraft Rocky Chunks	_______________________________________________________________________________________________________________________________________________________________________
val RockyChunk = {
	Iron : <ore:rockyChunkIron>,
	Gold : <ore:rockyChunkGold>,
	Copper : <ore:rockyChunkCopper>,
	Lead : <ore:rockyChunkLead>,
	Cobalt : <ore:rockyChunkCobalt>,
	Tungsten : <ore:rockyChunkTungsten>,
	Aluminum : <ore:rockyChunkAluminum>,
	Mithril : <ore:rockyChunkMithril>,
	Nickel : <ore:rockyChunkNickel>,
	Osmium : <ore:rockyChunkOsmium>,
	Silver : <ore:rockyChunkSilver>,
	Tin : <ore:rockyChunkTin>,
	Zinc : <ore:rockyChunkZinc>,
	antimony : <ore:rockyChunkAntimony>,
	ardite : <ore:rockyChunkArdite>,
	beryllium : <ore:rockyChunkBeryllium>,
	bismuth : <ore:rockyChunkBismuth>,
	boron : <ore:rockyChunkBoron>,
	cadmium : <ore:rockyChunkCadmium>,
	chromium : <ore:rockyChunkChromium>,
	coldiron : <ore:rockyChunkColdiron>,
	dilithium : <ore:rockyChunkDilithium>,
	iridium : <ore:rockyChunkIridium>,
	lithium : <ore:rockyChunkLithium>,
	magnesium : <ore:rockyChunkMagnesium>,
	manganese : <ore:rockyChunkManganese>,
	mercury : <ore:rockyChunkMercury>,
	platinum : <ore:rockyChunkPlatinum>,
	plutonium : <ore:rockyChunkPlutonium>,
	rutile : <ore:rockyChunkRutile>,
	starsteel : <ore:rockyChunkStarsteel>,
	tantalum : <ore:rockyChunkTantalum>,
	thorium : <ore:rockyChunkThorium>,
	titanium : <ore:rockyChunkTitanium>,
	uranium : <ore:rockyChunkUranium>,
	zirconium : <ore:rockyChunkZirconium>,
} as IOreDictEntry[string];

//	Dusts	_______________________________________________________________________________________________________________________________________________________________________
val Dust = {
	Iron : <ore:dustIron>,
	Gold : <ore:dustGold>,
	Copper : <ore:dustCopper>,
	Lead : <ore:dustLead>,
	Cobalt : <ore:dustCobalt>,
	Tungsten : <ore:dustTungsten>,
	Aluminum : <ore:dustAluminum>,
	Mithril : <ore:dustMithril>,
	Nickel : <ore:dustNickel>,
	Osmium : <ore:dustOsmium>,
	Silver : <ore:dustSilver>,
	Tin : <ore:dustTin>,
	Zinc : <ore:dustZinc>,
	antimony : <ore:dustAntimony>,
	ardite : <ore:dustArdite>,
	beryllium : <ore:dustBeryllium>,
	bismuth : <ore:dustBismuth>,
	boron : <ore:dustBoron>,
	cadmium : <ore:dustCadmium>,
	chromium : <ore:dustChromium>,
	coldiron : <ore:dustColdiron>,
	dilithium : <ore:dustDilithium>,
	iridium : <ore:dustIridium>,
	lithium : <ore:dustLithium>,
	magnesium : <ore:dustMagnesium>,
	manganese : <ore:dustManganese>,
	mercury : <ore:dustMercury>,
	platinum : <ore:dustPlatinum>,
	plutonium : <ore:dustPlutonium>,
	rutile : <ore:dustRutile>,
	starsteel : <ore:dustStarsteel>,
	tantalum : <ore:dustTantalum>,
	thorium : <ore:dustThorium>,
	titanium : <ore:dustTitanium>,
	uranium : <ore:dustUranium>,
	zirconium : <ore:dustZirconium>,
} as IOreDictEntry[string];

//	Mekanism DirtyDusts	_______________________________________________________________________________________________________________________________________________________________________
val DirtyDust = {
	Iron : <ore:dirtyDustIron>,
	Gold : <ore:dirtyDustGold>,
	Copper : <ore:dirtyDustCopper>,
	Lead : <ore:dirtyDustLead>,
	Cobalt : <ore:dirtyDustCobalt>,
	Tungsten : <ore:dirtyDustTungsten>,
	Aluminum : <ore:dirtyDustAluminum>,
	Mithril : <ore:dirtyDustMithril>,
	Nickel : <ore:dirtyDustNickel>,
	Osmium : <ore:dirtyDustOsmium>,
	Silver : <ore:dirtyDustSilver>,
	Tin : <ore:dirtyDustTin>,
	Zinc : <ore:dirtyDustZinc>,
	antimony : <ore:dirtyDustAntimony>,
	ardite : <ore:dirtyDustArdite>,
	beryllium : <ore:dirtyDustBeryllium>,
	bismuth : <ore:dirtyDustBismuth>,
	boron : <ore:dirtyDustBoron>,
	cadmium : <ore:dirtyDustCadmium>,
	chromium : <ore:dirtyDustChromium>,
	coldiron : <ore:dirtyDustColdiron>,
	dilithium : <ore:dirtyDustDilithium>,
	iridium : <ore:dirtyDustIridium>,
	lithium : <ore:dirtyDustLithium>,
	magnesium : <ore:dirtyDustMagnesium>,
	manganese : <ore:dirtyDustManganese>,
	mercury : <ore:dirtyDustMercury>,
	platinum : <ore:dirtyDustPlatinum>,
	plutonium : <ore:dirtyDustPlutonium>,
	rutile : <ore:dirtyDustRutile>,
	starsteel : <ore:dirtyDustStarsteel>,
	tantalum : <ore:dirtyDustTantalum>,
	thorium : <ore:dirtyDustThorium>,
	titanium : <ore:dirtyDustTitanium>,
	uranium : <ore:dirtyDustUranium>,
	zirconium : <ore:dirtyDustZirconium>,
} as IOreDictEntry[string];

//	Mekanism Clumps	_______________________________________________________________________________________________________________________________________________________________________
val Clump = {
	Iron : <ore:clumpIron>,
	Gold : <ore:clumpGold>,
	Copper : <ore:clumpCopper>,
	Lead : <ore:clumpLead>,
	Cobalt : <ore:clumpCobalt>,
	Tungsten : <ore:clumpTungsten>,
	Aluminum : <ore:clumpAluminum>,
	Mithril : <ore:clumpMithril>,
	Nickel : <ore:clumpNickel>,
	Osmium : <ore:clumpOsmium>,
	Silver : <ore:clumpSilver>,
	Tin : <ore:clumpTin>,
	Zinc : <ore:clumpZinc>,
	antimony : <ore:clumpAntimony>,
	ardite : <ore:clumpArdite>,
	beryllium : <ore:clumpBeryllium>,
	bismuth : <ore:clumpBismuth>,
	boron : <ore:clumpBoron>,
	cadmium : <ore:clumpCadmium>,
	chromium : <ore:clumpChromium>,
	coldiron : <ore:clumpColdiron>,
	dilithium : <ore:clumpDilithium>,
	iridium : <ore:clumpIridium>,
	lithium : <ore:clumpLithium>,
	magnesium : <ore:clumpMagnesium>,
	manganese : <ore:clumpManganese>,
	mercury : <ore:clumpMercury>,
	platinum : <ore:clumpPlatinum>,
	plutonium : <ore:clumpPlutonium>,
	rutile : <ore:clumpRutile>,
	starsteel : <ore:clumpStarsteel>,
	tantalum : <ore:clumpTantalum>,
	thorium : <ore:clumpThorium>,
	titanium : <ore:clumpTitanium>,
	uranium : <ore:clumpUranium>,
	zirconium : <ore:clumpZirconium>,
} as IOreDictEntry[string];